// SPDX-FileCopyrightText: 2026 Iya CyberSecurity Solutions, LLC
// SPDX-License-Identifier: BUSL-1.1

//! Every way this service can fail or refuse has a code,
//! `STS-<SUBSYSTEM>-<NNNN>`, in ONE table — `common/error_codes.js` until the
//! cutover, exported to `data/error_codes.json` (rust/DESIGN.md section 4.4).
//! **A code is an operator's name and is RECORDED, NEVER SENT**: it goes at
//! the front of a log line ([`crate::log::tag`]) and on an audit row, never
//! in a response.
//!
//! Each code is a constant in [`codes`], generated by `build.rs`, so a code
//! that is not in the table does not compile — the check
//! `tests/error_codes.js` makes by scanning, made by the compiler instead:
//!
//! ```
//! use sts_core::errors::codes;
//! use sts_core::log::tag;
//!
//! assert_eq!(tag(codes::STS_XPEP_0013), "[STS-XPEP-0013] ");
//! assert_eq!(codes::STS_XPEP_0013.subsystem(), "XPEP");
//! assert!(codes::STS_XPEP_0013.row().is_some());
//! ```

use std::collections::HashMap;
use std::fmt;
use std::sync::LazyLock;

/// One code. Made only by the generated constants.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ErrorCode(&'static str);

/// A row of the table.
#[derive(Debug, PartialEq, Eq)]
pub struct Row {
    pub code: &'static str,
    /// What happened, for an operator.
    pub summary: &'static str,
    /// What the client is answered instead, by its own specification.
    pub spec: &'static str,
    /// The condition no longer exists; the row stays so the code is never
    /// reused.
    pub retired: bool,
}

/// A subsystem codes are grouped by.
#[derive(Debug, PartialEq, Eq)]
pub struct Subsystem {
    pub id: &'static str,
    pub label: &'static str,
    /// The files it is raised from (`where` in the table).
    pub location: &'static str,
    pub what: &'static str,
}

/// The constants, one per code.
#[allow(dead_code)]
pub mod codes {
    use super::{ErrorCode, Row, Subsystem};
    include!(concat!(env!("OUT_DIR"), "/error_codes.rs"));
}

static BY_CODE: LazyLock<HashMap<&'static str, &'static Row>> =
    LazyLock::new(|| codes::ROWS.iter().map(|row| (row.code, row)).collect());

impl ErrorCode {
    pub const fn as_str(self) -> &'static str {
        self.0
    }

    /// Its row. Always present for a generated constant.
    pub fn row(self) -> Option<&'static Row> {
        describe(self.0)
    }

    /// `STS-XPEP-0013` → `XPEP`.
    pub fn subsystem(self) -> &'static str {
        subsystem_of(self.0).unwrap_or("")
    }
}

impl fmt::Display for ErrorCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.0)
    }
}

impl AsRef<str> for ErrorCode {
    fn as_ref(&self) -> &str {
        self.0
    }
}

/// `STS-<SUBSYSTEM>-<NNNN>`: a capital, one to nine capitals or digits,
/// four digits.
pub fn is_well_formed(code: &str) -> bool {
    let mut parts = code.split('-');
    let (Some("STS"), Some(subsystem), Some(number), None) =
        (parts.next(), parts.next(), parts.next(), parts.next())
    else {
        return false;
    };
    let mut letters = subsystem.chars();
    letters.next().is_some_and(|c| c.is_ascii_uppercase())
        && (1..=9).contains(&letters.clone().count())
        && letters.all(|c| c.is_ascii_uppercase() || c.is_ascii_digit())
        && number.len() == 4
        && number.chars().all(|c| c.is_ascii_digit())
}

/// The row for a code given as text, as a log line or a stored audit row
/// carries it.
pub fn describe(code: &str) -> Option<&'static Row> {
    BY_CODE.get(code).copied()
}

pub fn is_known(code: &str) -> bool {
    describe(code).is_some()
}

/// The subsystem part of a well-formed code.
pub fn subsystem_of(code: &str) -> Option<&'static str> {
    if !is_well_formed(code) {
        return None;
    }
    let id = code.split('-').nth(1)?;
    subsystems().iter().find(|s| s.id == id).map(|s| s.id)
}

/// Every row, in the table's order.
pub fn rows() -> &'static [Row] {
    codes::ROWS
}

/// Every subsystem, in documentation order.
pub fn subsystems() -> &'static [Subsystem] {
    codes::SUBSYSTEMS
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_table_is_whole_and_well_formed() {
        assert!(rows().len() > 4000);
        let mut seen = std::collections::HashSet::new();
        for row in rows() {
            assert!(is_well_formed(row.code), "{}", row.code);
            assert!(seen.insert(row.code), "{} twice", row.code);
            assert!(subsystem_of(row.code).is_some(), "{}", row.code);
            assert!(!row.summary.is_empty(), "{}", row.code);
        }
    }

    #[test]
    fn well_formed_is_the_registry_pattern() {
        assert!(is_well_formed("STS-CORE-0001"));
        // Codes not in the table are built rather than written, so
        // tests/error_codes.js does not read them as uses.
        let made = |subsystem: &str, number: &str| {
            format!("STS-{}-{}", subsystem, number)
        };
        assert!(is_well_formed(&made("X9", "0001")));
        assert!(!is_well_formed("STS-CORE-001"));
        assert!(!is_well_formed("STS-core-0001"));
        assert!(!is_well_formed("STS-9X-0001"));
        assert!(!is_well_formed("STS-ABCDEFGHIJK-0001"));
        assert!(!is_well_formed("STS-CORE-0001-1"));
        assert!(!is_well_formed("XTS-CORE-0001"));
    }

    #[test]
    fn a_retired_code_is_known_and_marked() {
        let row = describe("STS-XPEP-0001");
        assert!(row.is_some_and(|r| r.retired));
        assert!(!describe("STS-XPEP-0013").is_some_and(|r| r.retired));
        assert!(describe(&format!("STS-{}-0001", "NOPE")).is_none());
    }
}
