// @ts-check
// SPDX-FileCopyrightText: 2026 Iya CyberSecurity Solutions, LLC
// SPDX-License-Identifier: BUSL-1.1

'use strict';
//
// File: persistence/directory_codec.js
//
// ===========================================================================
// A DIRECTORY ENTRY IS STORED SEALED (#391 phase 6, #222, 2026-10-01).
//
// rcbj's decision on #391: each entry's attributes are sealed as ONE blob
// under its realm's `directory` data key — a person's under the home cell's
// where the cell holds a key — in `sts_ldap_entries.attrs`; the DN stays
// readable, and so does every lookup and cross-entry reference that is a DN.
// The lookups that read a VALUE are kept indexed by columns this module
// computes and the service writes (they were generated by the database from
// the plaintext): each a KEYED DIGEST (`keystore.keyedDigest()`, the digest
// key every node holds), so an exact match is still one indexed probe and
// nothing in the column says what it matched.
//
//   name_keys   the `uid` values, lower-cased      — `byName()`
//   mail_keys   `mail`, lower-cased                — `byMail()`
//   uuid_keys   `entryUUID` and its aliases        — `byUuid()`
//   class_keys  `objectClass`, lower-cased         — `classesUnder()`
//   value_keys  `name=value` of VALUE_INDEXED       — `byAttribute()`
//   attr_names  the attribute NAMES, in the clear  — `withAttribute()`
//
// Attribute names are not a person's data (every person has a `mail`), and
// "who holds a credential of this kind" is a question the windowed directory
// asks of the store, so they stay readable.
//
// **THE BLOB NAMES ITS DN.** What is sealed is `{ "dn": <dn_key>, "a":
// <attributes> }`, and an open refuses a blob whose DN is not its row's: a
// blob copied onto another entry's row does not open as that entry.
//
// **WHERE NOTHING DURABLE SEALS, NOTHING IS SEALED** — development, a key that
// dies with the process: the attributes go in as the JSON object they always
// were, and the lookup columns hold `<kind>\n<value>` in the clear (a digest
// needs a key). Every reader takes either shape, so the two can meet
// in one table during a test.
//
// THE QUERIES' TWO HALVES ARE HERE, NOT IN `directory_queries.js`: a question
// is BUILT and its rows turned into entries on whatever thread asks the
// database — the bridge's has no keystore — so a value to look up is keyed
// HERE first (`keyArgs()`) and an answer opened HERE after (`openAnswer()`),
// on the thread that holds the keys.
// ===========================================================================

const bunyan = require('bunyan');

const log = bunyan.createLogger({ name: 'sts-directory-codec' });

const LABEL = 'directory';
const DIGEST_LABEL = 'directory-index';

// The attributes whose values `byAttribute()` looks up — as written, not
// lower-cased, because those lookups compare a value exactly (a DID, a SPIFFE
// ID, a certificate subject, a login name, a federation link).
const VALUE_INDEXED = ['uid', 'didsubject', 'spiffesubject', 'x509subject',
                       'federationlink'];

function keystore() {
  log.debug("Entering keystore().");
  log.debug("Leaving keystore().");
  return require('../common/keystore');
}

// Whether values written now are sealed: a durable key-encryption key.
function sealing() {
  log.debug("Entering sealing().");
  const ks = keystore();
  log.debug("Leaving sealing().");
  return ks.persists() && ks.sealed();
}

/**
 * The lookup form of one value: its keyed digest under `kind`, or the value
 * itself where no digest key is held.
 *
 * @param kind - what the value is (`name`, `mail`, `uuid`, `class`, or
 *   `attr:<name>`)
 * @param value - the value, already in its compared form
 * @returns the column value
 */
function lookupOf(kind, value) {
  log.debug("Entering lookupOf().");
  const text = String(value == null ? '' : value);
  // DIGESTED ON THE SAME CONDITION THE BLOB IS SEALED: a durable key. A
  // per-run key would write digests the next run cannot reproduce, against
  // rows that outlive it.
  const ks = keystore();
  const digest = sealing() && typeof ks.keyedDigest === 'function'
    ? ks.keyedDigest(DIGEST_LABEL, String(kind) + '\n' + text) : null;
  log.debug("Leaving lookupOf().");
  // Without a key the KIND still goes in front, so that one value of two
  // attributes (a `uid` and a `federationlink` both "x") are two lookups.
  return digest || (String(kind) + '\n' + text);
}

// The values of an attribute, by name in any case, as an array of strings.
function valuesOf(attrs, name) {
  log.debug("Entering valuesOf().");
  const out = [];
  Object.keys(attrs || {}).forEach(function (key) {
    if (key.toLowerCase() !== name) {
      return;
    }
    const v = attrs[key];
    (Array.isArray(v) ? v : [v]).forEach(function (one) {
      if (one !== null && one !== undefined) {
        out.push(String(one));
      }
    });
  });
  log.debug("Leaving valuesOf().");
  return out;
}

function lowered(list) {
  log.debug("Entering lowered().");
  log.debug("Leaving lowered().");
  return list.map(function (one) {
    return one.toLowerCase();
  });
}

function unique(list) {
  log.debug("Entering unique().");
  log.debug("Leaving unique().");
  return Array.from(new Set(list));
}

/**
 * The lookup columns of an entry's attributes.
 *
 * @param attrs - the attributes, plaintext
 * @returns `{ nameKeys, mailKeys, uuidKeys, classKeys, valueKeys, attrNames }`
 */
function indexOf(attrs) {
  log.debug("Entering indexOf().");
  const a = attrs || {};
  const keyed = function (kind, list) {
    return unique(list).map(function (one) {
      return lookupOf(kind, one);
    });
  };
  const valueKeys = [];
  VALUE_INDEXED.forEach(function (name) {
    unique(valuesOf(a, name)).forEach(function (one) {
      valueKeys.push(lookupOf('attr:' + name, one));
    });
  });
  const out = {
    nameKeys: keyed('name', lowered(valuesOf(a, 'uid'))),
    mailKeys: keyed('mail', lowered(valuesOf(a, 'mail'))),
    uuidKeys: keyed('uuid', lowered(valuesOf(a, 'entryuuid')
      .concat(valuesOf(a, 'stsentryuuidalias')))),
    classKeys: keyed('class', lowered(valuesOf(a, 'objectclass'))),
    valueKeys: valueKeys,
    attrNames: unique(Object.keys(a).map(function (one) {
      return one.toLowerCase();
    }))
  };
  log.debug("Leaving indexOf().");
  return out;
}

/**
 * Builds the codec one driver uses: `tier` is the data-key tier its entries
 * are sealed under — `cell` for a store of people (a cell's own database, or
 * the one database of a single-cell service, where `cell` is the service's
 * key), `service` for the global tier.
 *
 * @param tier - `cell` or `service`
 * @returns the codec
 */
function create(tier) {
  log.debug("Entering create(). " + tier);
  const codecTier = tier === 'service' ? 'service' : 'cell';
  const codec = {
    tier: codecTier,
    /**
     * The `attrs` column value for an entry: the sealed blob (a JSON string)
     * or the attributes themselves.
     */
    sealAttributes: function (realmId, dnKey, attrs) {
      log.debug("Entering codec.sealAttributes().");
      if (!sealing()) {
        log.debug("Leaving codec.sealAttributes(). Not sealing.");
        return attrs || {};
      }
      const blob = keystore().seal(JSON.stringify({ dn: String(dnKey),
                                                    a: attrs || {} }),
                                   LABEL, codecTier,
                                   { realm: String(realmId || '') });
      log.debug("Leaving codec.sealAttributes().");
      return blob;
    },
    /**
     * The attributes from an `attrs` column value, or null for a blob that
     * does not open or names another DN.
     */
    openAttributes: function (dnKey, stored) {
      log.debug("Entering codec.openAttributes().");
      if (stored === null || stored === undefined) {
        log.debug("Leaving codec.openAttributes(). Nothing.");
        return {};
      }
      if (typeof stored !== 'string') {
        log.debug("Leaving codec.openAttributes(). Plain.");
        return stored;
      }
      const text = keystore().open(stored, LABEL);
      if (text === null || text === undefined) {
        log.debug("Leaving codec.openAttributes(). Does not open.");
        return null;
      }
      let parsed = null;
      try {
        parsed = JSON.parse(text);
      } catch (e) {
        log.debug("Caught in codec.openAttributes(): " +
                  ((e && e.message) || e));
        parsed = null;
      }
      if (!parsed || typeof parsed !== 'object' ||
          (dnKey !== undefined && dnKey !== null &&
           String(parsed.dn) !== String(dnKey))) {
        log.debug("Leaving codec.openAttributes(). Not this entry's.");
        return null;
      }
      log.debug("Leaving codec.openAttributes().");
      return parsed.a || {};
    },
    index: indexOf
  };
  log.debug("Leaving create().");
  return codec;
}

/**
 * A query's arguments with every value it looks up turned into its lookup
 * form, for the thread that builds the statement (`directory_queries.js`).
 *
 * @param name - the query's name
 * @param args - its arguments as the directory asks them
 * @returns the arguments the builder takes
 */
function keyArgs(name, args) {
  log.debug("Entering keyArgs(). " + name);
  const a = Array.isArray(args) ? args.slice() : [];
  const lower = function (v) {
    return String(v == null ? '' : v).trim().toLowerCase();
  };
  if (name === 'byName') {
    const wanted = lower(a[2]);
    a[2] = { key: lookupOf('name', wanted), rdn: wanted };
  } else if (name === 'byUuid') {
    a[1] = { key: lookupOf('uuid', lower(a[1])) };
  } else if (name === 'byMail') {
    a[1] = { key: lookupOf('mail', lower(a[1])) };
  } else if (name === 'byAttribute') {
    a[2] = { key: lookupOf('attr:' + lower(a[1]), String(a[2])) };
  } else if (name === 'classesUnder') {
    a[2] = (a[2] || []).map(function (one) {
      return { key: lookupOf('class', lower(one)) };
    });
  }
  log.debug("Leaving keyArgs().");
  return a;
}

/**
 * A query's answer with every entry's attributes opened, on the thread that
 * holds the keys. A row whose blob does not open is dropped with a warning:
 * an entry this process cannot read is one it cannot answer about.
 *
 * @param codec - the driver's codec
 * @param name - the query's name
 * @param answer - what `directory_queries.answerOf()` gave
 * @returns the answer
 */
function openAnswer(codec, name, answer) {
  log.debug("Entering openAnswer(). " + name);
  if (!Array.isArray(answer)) {
    log.debug("Leaving openAnswer(). Not rows.");
    return answer;
  }
  const out = [];
  answer.forEach(function (row) {
    if (name === 'namesUnder') {
      const attrs = codec.openAttributes(row.key, row.attrs);
      const uid = attrs ? valuesOf(attrs, 'uid')[0] || '' : '';
      out.push({ key: row.key, dn: row.dn, origin: row.origin,
                 uid: row.uid || uid });
      return;
    }
    const attrs = codec.openAttributes(row.key, row.entry &&
                                       row.entry.attributes);
    if (attrs === null) {
      log.warn(require('../common/error_codes').tag('STS-STORE-0072') +
               'persistence: the directory entry ' + row.key + ' in the "' +
               row.realm + '" realm is sealed and did not open here; it is ' +
               'left out of the answer.');
      return;
    }
    out.push(Object.assign({}, row, { entry: Object.assign({}, row.entry,
                                                           { attributes:
                                                             attrs }) }));
  });
  log.debug("Leaving openAnswer().");
  return out;
}

module.exports = {
  LABEL: LABEL,
  VALUE_INDEXED: VALUE_INDEXED,
  create: create,
  // The same, for the postgres driver, whose own factory is `create()`: a
  // `create(` in its body reads to tests/no_periodic_timers.js as the
  // factory calling itself.
  codecFor: create,
  indexOf: indexOf,
  lookupOf: lookupOf,
  keyArgs: keyArgs,
  openAnswer: openAnswer
};
