// @ts-check
// SPDX-FileCopyrightText: 2026 Iya CyberSecurity Solutions, LLC
// SPDX-License-Identifier: BUSL-1.1

'use strict';
//
// File: persistence/directory_queries.js
//
// ===========================================================================
// THE DIRECTORY'S LOOKUPS AS SQL (#349 phase 2, 2026-09-29).
//
// A request or surface worker in `ldap.workerDirectory=postgres-lru` holds the
// large containers of the directory — the people under `ou=users` and the
// devices under `ou=devices` — as a bounded window rather than whole, and asks
// the store for what the window does not hold. Every question it can ask is a
// function here that BUILDS a statement (`{ text, values }`) and nothing else.
// Two things run them:
//
//   * `persistence_postgres.js`'s `directoryQuery()`, asynchronously, on the
//     driver's read pool — what the tests drive against the stand-in `pg`,
//     and what an async caller uses;
//   * `common/sync_query_thread.ts`, the bridge's thread, on a connection of
//     its own, so that the directory's SYNCHRONOUS API can ask (phase 3).
//
// ONE FILE FOR BOTH, because two copies of a WHERE clause are two answers to
// "who is alice", and the day they disagree a login name is unique on one
// door and not on the other.
//
// **THE COLUMNS THESE READ** (schema version 14): `parent_key` and
// `rdn_value` are GENERATED by the database from `dn_key`; `name_keys`,
// `mail_keys`, `uuid_keys`, `class_keys`, `value_keys` and `attr_names` are
// WRITTEN by the service beside the entry, because since #391 phase 6
// `attrs` is a sealed blob the database cannot read
// (`persistence/directory_codec.js`): keyed digests of the values, which is
// why a lookup's value arrives keyed (see `keyed()` below). They mirror
// `ldap/ldap_server.js`'s own rules:
//
//   * `parent_key` is `parentDn()` of the key: everything after the first
//     comma. `normalizeDn()` splits on every comma without reading escapes,
//     and so does this — the same simplification, on purpose.
//   * `rdn_value` is the first RDN's value, lower-cased (the key is), still
//     DN-escaped. `usernameOfEntry()` unescapes; a name whose RDN carries an
//     escape is matched through `name_keys` (its `uid`) instead.
//   * `name_keys` is the entry's `uid` values, lower-cased: with `rdn_value`,
//     the pair `usernameKeysOf()` indexes.
//   * `mail_keys` is `mail`, lower-cased; `uuid_keys` is `entryUUID` and its
//     aliases (`stsEntryUuidAlias`), lower-cased.
//
// **LOWER-CASING IS THE DATABASE'S `lower()` ON ONE SIDE AND JAVASCRIPT'S
// `toLowerCase()` ON THE OTHER.** They agree on every character this
// service's names are built from; for the few Unicode characters whose case
// mapping depends on a collation they may not, and a row found here is always
// checked again by the caller with the service's own rule. What that cannot
// repair is a row NOT found, so a name outside that agreement is the one
// place a SQL lookup can say "nobody" where the in-memory index would have
// found somebody. It is stated here rather than discovered.
//
// A ROW is `{ realm, key, entry }`, `entry` the directory's own shape
// (`{ dn, attributes, origin, createdAt, modifiedAt }`) — `rowOf()` below,
// which the driver's `readEntry()` already answered with.
// ===========================================================================

const bunyan = require('bunyan');

const log = bunyan.createLogger({ name: 'sts-directory-queries' });

// The columns every lookup selects, and the order `rowOf()` reads them in.
const COLUMNS = 'realm, dn_key, dn, attrs, origin, created_at, modified_at';

// ---------------------------------------------------------------------------
// A VALUE IS LOOKED UP IN ITS LOOKUP FORM (#391 phase 6). The lookup columns
// hold keyed digests the service writes (`directory_codec.js`), and this
// builder runs where no key is held — the bridge's thread — so the value to
// look up arrives KEYED already: `{ key }` (and `{ key, rdn }` for a name),
// made by `directory_codec.keyArgs()` on the thread that asked. A raw value
// (a test calling a builder directly) is put in the keyless form the codec
// writes where no key is held: `<kind>\n<value>`.
// ---------------------------------------------------------------------------
function keyed(arg, kind, lower) {
  log.debug("Entering keyed().");
  if (arg && typeof arg === 'object' &&
      Object.prototype.hasOwnProperty.call(arg, 'key')) {
    log.debug("Leaving keyed(). Keyed already.");
    return String(arg.key);
  }
  const text = String(arg == null ? '' : arg).trim();
  log.debug("Leaving keyed().");
  return kind + '\n' + (lower ? text.toLowerCase() : text);
}

// A DN key strictly under `baseKey`, or `baseKey` itself when `self` is true.
// `right()` rather than `LIKE`, so a `%` or `_` in a DN is not a wildcard.
// `$n` and `$m` are the positions of the base and its length in `values`.
function underClause(baseAt, lengthAt, self) {
  log.debug("Entering underClause().");
  const strict = 'right(dn_key, $' + lengthAt + ') = \',\' || $' + baseAt;
  log.debug("Leaving underClause().");
  return self ? '(dn_key = $' + baseAt + ' OR ' + strict + ')' : strict;
}

// The length `right()` compares: the base and the comma before it.
function suffixLength(baseKey) {
  log.debug("Entering suffixLength().");
  log.debug("Leaving suffixLength().");
  return String(baseKey).length + 1;
}

// A bound on a page, so no caller can ask for the table in one statement.
const MAX_PAGE = 1000;

function pageSize(limit) {
  log.debug("Entering pageSize().");
  const n = Math.floor(Number(limit));
  log.debug("Leaving pageSize().");
  return isFinite(n) && n >= 1 ? Math.min(n, MAX_PAGE) : MAX_PAGE;
}

/**
 * The entries at a list of keys.
 *
 * @param realm - the realm id
 * @param keys - normalised DNs
 * @returns the statement
 */
function byKeys(realm, keys) {
  log.debug("Entering byKeys().");
  log.debug("Leaving byKeys().");
  return { text: 'SELECT ' + COLUMNS + ' FROM sts_ldap_entries WHERE ' +
                 'realm = $1 AND dn_key = ANY($2::text[]) ORDER BY dn_key',
           values: [String(realm), (keys || []).map(String)] };
}

/**
 * The entries directly under a container that answer to a login name: a
 * `uid` value or the RDN value, compared lower-cased. `existingUserEntry()`'s
 * question; first by key wins, as a restored process's index does.
 *
 * @param realm - the realm id
 * @param parentKey - the container's normalised DN (`ou=users,<base>`)
 * @param name - the name, as typed
 * @returns the statement
 */
function byName(realm, parentKey, name) {
  log.debug("Entering byName().");
  // The RDN is the DN's, readable; the `uid` is a lookup form.
  const rdn = name && typeof name === 'object'
    ? String(name.rdn || '')
    : String(name == null ? '' : name).trim().toLowerCase();
  log.debug("Leaving byName().");
  return { text: 'SELECT ' + COLUMNS + ' FROM sts_ldap_entries WHERE ' +
                 'realm = $1 AND parent_key = $2 AND (name_keys @> $3::jsonb ' +
                 'OR rdn_value = $4) ORDER BY dn_key LIMIT 2',
           values: [String(realm), String(parentKey),
                    JSON.stringify([keyed(name, 'name', true)]), rdn] };
}

/**
 * The entries holding an `entryUUID` or an alias of one, lower-cased.
 *
 * @param realm - the realm id
 * @param uuid - the UUID, bare
 * @returns the statement
 */
function byUuid(realm, uuid) {
  log.debug("Entering byUuid().");
  log.debug("Leaving byUuid().");
  return { text: 'SELECT ' + COLUMNS + ' FROM sts_ldap_entries WHERE ' +
                 'realm = $1 AND uuid_keys @> $2::jsonb ORDER BY dn_key ' +
                 'LIMIT 8',
           values: [String(realm), JSON.stringify([keyed(uuid, 'uuid',
                                                         true)])] };
}

/**
 * The entries holding a mail address, compared lower-cased.
 *
 * @param realm - the realm id
 * @param mail - the address
 * @param limit - at most this many rows
 * @returns the statement
 */
function byMail(realm, mail, limit) {
  log.debug("Entering byMail().");
  log.debug("Leaving byMail().");
  return { text: 'SELECT ' + COLUMNS + ' FROM sts_ldap_entries WHERE ' +
                 'realm = $1 AND mail_keys @> $2::jsonb ORDER BY dn_key ' +
                 'LIMIT $3',
           values: [String(realm), JSON.stringify([keyed(mail, 'mail',
                                                         true)]),
                    pageSize(limit)] };
}

/**
 * The entries holding exactly this value of an attribute (case as stored),
 * through the GIN index over `attrs`. For the lookups that compare a value
 * as written — a DID, a SPIFFE ID, a federation link.
 *
 * @param realm - the realm id
 * @param attribute - the attribute name, lower-cased as the store holds it
 * @param value - the value
 * @param limit - at most this many rows
 * @returns the statement
 */
function byAttribute(realm, attribute, value, limit) {
  log.debug("Entering byAttribute().");
  const name = String(attribute).toLowerCase();
  log.debug("Leaving byAttribute().");
  return { text: 'SELECT ' + COLUMNS + ' FROM sts_ldap_entries WHERE ' +
                 'realm = $1 AND value_keys @> $2::jsonb ORDER BY dn_key ' +
                 'LIMIT $3',
           values: [String(realm),
                    JSON.stringify([keyed(value, 'attr:' + name, false)]),
                    pageSize(limit)] };
}

/**
 * One page of the entries under a base, in key order after `afterKey`.
 *
 * @param realm - the realm id
 * @param baseKey - the base's normalised DN
 * @param afterKey - the last key of the previous page, or ''
 * @param limit - the page size (at most 1,000)
 * @param options - `self` to include the base itself, `oneLevel` for its
 *   children only
 * @returns the statement
 */
function page(realm, baseKey, afterKey, limit, options) {
  log.debug("Entering page().");
  const o = options || {};
  const where = o.oneLevel
    ? 'parent_key = $2'
    : underClause(2, 5, !!o.self);
  log.debug("Leaving page().");
  return { text: 'SELECT ' + COLUMNS + ' FROM sts_ldap_entries WHERE ' +
                 'realm = $1 AND ' + where + ' AND dn_key > $3 ORDER BY ' +
                 'dn_key LIMIT $4',
           values: o.oneLevel
             ? [String(realm), String(baseKey), String(afterKey || ''),
                pageSize(limit)]
             : [String(realm), String(baseKey), String(afterKey || ''),
                pageSize(limit), suffixLength(baseKey)] };
}

/**
 * How many entries are under a base (strictly), or in the whole realm when
 * the base is ''.
 *
 * @param realm - the realm id
 * @param baseKey - the base's normalised DN, or '' for the realm
 * @returns the statement; its one row's `n` is the count
 */
function count(realm, baseKey) {
  log.debug("Entering count().");
  if (!baseKey) {
    log.debug("Leaving count(). The realm.");
    return { text: 'SELECT count(*)::bigint AS n FROM sts_ldap_entries ' +
                   'WHERE realm = $1', values: [String(realm)] };
  }
  log.debug("Leaving count().");
  return { text: 'SELECT count(*)::bigint AS n FROM sts_ldap_entries WHERE ' +
                 'realm = $1 AND ' + underClause(2, 3, false),
           values: [String(realm), String(baseKey), suffixLength(baseKey)] };
}

/**
 * Whether anything is under a key: `hasChildren()`'s question.
 *
 * @param realm - the realm id
 * @param key - the entry's normalised DN
 * @returns the statement; a row means yes
 */
function hasChild(realm, key) {
  log.debug("Entering hasChild().");
  log.debug("Leaving hasChild().");
  return { text: 'SELECT 1 AS one FROM sts_ldap_entries WHERE realm = $1 ' +
                 'AND ' + underClause(2, 3, false) + ' LIMIT 1',
           values: [String(realm), String(key), suffixLength(key)] };
}

/**
 * One page of the entries under a base that HOLD an attribute (any value),
 * in key order after `afterKey`. `attr_names ? name` has no index behind it here
 * and is a scan of the realm's rows under the base; it answers only the
 * holders, which is what the lists of who holds a credential need.
 *
 * @param realm - the realm id
 * @param baseKey - the base's normalised DN
 * @param attribute - the attribute name, lower-cased as the store holds it
 * @param afterKey - the last key of the previous page, or ''
 * @param limit - the page size (at most 1,000)
 * @returns the statement
 */
function withAttribute(realm, baseKey, attribute, afterKey, limit) {
  log.debug("Entering withAttribute().");
  log.debug("Leaving withAttribute().");
  return { text: 'SELECT ' + COLUMNS + ' FROM sts_ldap_entries WHERE ' +
                 'realm = $1 AND ' + underClause(2, 6, false) + ' AND ' +
                 'attr_names ? $3 AND dn_key > $4 ORDER BY dn_key LIMIT $5',
           values: [String(realm), String(baseKey),
                    String(attribute).toLowerCase(), String(afterKey || ''),
                    pageSize(limit), suffixLength(baseKey)] };
}

/**
 * Whether any entry of a realm holds an attribute.
 *
 * @param realm - the realm id
 * @param attribute - the attribute name, lower-cased as the store holds it
 * @returns the statement; a row means yes
 */
function anyWithAttribute(realm, attribute) {
  log.debug("Entering anyWithAttribute().");
  log.debug("Leaving anyWithAttribute().");
  return { text: 'SELECT 1 AS one FROM sts_ldap_entries WHERE realm = $1 ' +
                 'AND attr_names ? $2 LIMIT 1',
           values: [String(realm), String(attribute).toLowerCase()] };
}

/**
 * The entries strictly under a base holding any of the given object classes
 * (lower-cased), through the GIN index over `class_keys`: the groups a
 * windowed worker must see although it does not hold their container.
 *
 * @param realm - the realm id
 * @param baseKey - the base's normalised DN
 * @param classes - the object classes, lower-cased
 * @returns the statement
 */
function classesUnder(realm, baseKey, classes) {
  log.debug("Entering classesUnder().");
  log.debug("Leaving classesUnder().");
  return { text: 'SELECT ' + COLUMNS + ' FROM sts_ldap_entries WHERE ' +
                 'realm = $1 AND ' + underClause(2, 4, false) + ' AND ' +
                 'class_keys ?| $3::text[] ORDER BY dn_key',
           values: [String(realm), String(baseKey),
                    (classes || []).map(function (one) {
                      return keyed(one, 'class', true);
                    }), suffixLength(baseKey)] };
}

/**
 * One page of the entries under a base as NAMES only — the key, the DN as
 * written, the origin and the first `uid` — for the identity register a
 * windowed worker fills at start without reading a single entry whole.
 *
 * @param realm - the realm id
 * @param baseKey - the base's normalised DN
 * @param afterKey - the last key of the previous page, or ''
 * @param limit - the page size (at most 1,000)
 * @returns the statement
 */
function namesUnder(realm, baseKey, afterKey, limit) {
  log.debug("Entering namesUnder().");
  log.debug("Leaving namesUnder().");
  // `attrs` whole, not `attrs->'uid'`: it is a sealed blob (#391 phase 6),
  // and the `uid` is read out of it by `directory_codec.openAnswer()`.
  return { text: 'SELECT dn_key, dn, origin, attrs ' +
                 'FROM sts_ldap_entries WHERE realm = $1 AND ' +
                 underClause(2, 5, false) + ' AND dn_key > $3 ORDER BY ' +
                 'dn_key LIMIT $4',
           values: [String(realm), String(baseKey), String(afterKey || ''),
                    pageSize(limit), suffixLength(baseKey)] };
}

/**
 * Every entry EXCEPT those strictly under the given containers, for the
 * restore of a worker that holds those containers as a window.
 *
 * @param windowed - `[{ realm, baseKey }]`, the containers not restored
 * @returns the statement
 */
function residentOnly(windowed) {
  log.debug("Entering residentOnly().");
  const list = windowed || [];
  log.debug("Leaving residentOnly().");
  return { text: 'SELECT ' + COLUMNS + ' FROM sts_ldap_entries e WHERE NOT ' +
                 'EXISTS (SELECT 1 FROM unnest($1::text[], $2::text[]) AS ' +
                 'w(r, c) WHERE w.r = e.realm AND right(e.dn_key, ' +
                 'length(w.c) + 1) = \',\' || w.c) ORDER BY realm, dn_key',
           values: [list.map(function (one) { return String(one.realm); }),
                    list.map(function (one) { return String(one.baseKey); })]
  };
}

/**
 * A result row in the directory's own shape.
 *
 * @param row - a row with the columns every lookup selects
 * @returns `{ realm, key, entry }`
 */
function rowOf(row) {
  log.debug("Entering rowOf().");
  log.debug("Leaving rowOf().");
  return { realm: row.realm, key: row.dn_key, entry: {
    dn: row.dn, attributes: row.attrs || {},
    origin: row.origin || undefined,
    createdAt: row.created_at || null,
    modifiedAt: row.modified_at || row.created_at || null } };
}

/**
 * The answer to a named query from its result rows: rows in the directory's
 * shape, except `count` (a number) and `hasChild` (a boolean).
 *
 * @param name - the query's name
 * @param rows - the result rows
 * @returns the answer
 */
function answerOf(name, rows) {
  log.debug("Entering answerOf().");
  const list = Array.isArray(rows) ? rows : [];
  if (name === 'count') {
    log.debug("Leaving answerOf(). A count.");
    return Number((list[0] || {}).n || 0);
  }
  if (name === 'hasChild' || name === 'anyWithAttribute') {
    log.debug("Leaving answerOf(). A yes or a no.");
    return list.length > 0;
  }
  if (name === 'namesUnder') {
    log.debug("Leaving answerOf(). Names.");
    return list.map(function (row) {
      // A plain entry's `uid` is read here; a sealed one's is read by
      // `directory_codec.openAnswer()`, which is handed the blob.
      const plain = row.attrs && typeof row.attrs === 'object'
        ? row.attrs : null;
      const uid = plain && Array.isArray(plain.uid) ? plain.uid[0]
        : plain ? plain.uid : '';
      return { key: row.dn_key, dn: row.dn, origin: row.origin || '',
               uid: uid === null || uid === undefined ? '' : String(uid),
               attrs: plain ? undefined : row.attrs };
    });
  }
  log.debug("Leaving answerOf().");
  return list.map(rowOf);
}

// THE QUERIES BY NAME, which is how a caller on the far side of a thread
// boundary names one: a function cannot be posted to a worker thread.
const QUERIES = {
  byKeys: byKeys,
  byName: byName,
  byUuid: byUuid,
  byMail: byMail,
  byAttribute: byAttribute,
  page: page,
  count: count,
  hasChild: hasChild,
  withAttribute: withAttribute,
  anyWithAttribute: anyWithAttribute,
  classesUnder: classesUnder,
  namesUnder: namesUnder,
  residentOnly: residentOnly
};

/**
 * Builds a named query.
 *
 * @param name - one of the names in `QUERIES`
 * @param args - its arguments, in order
 * @returns the statement
 * @throws an Error naming an unknown query
 */
function build(name, args) {
  log.debug("Entering build().");
  const f = Object.prototype.hasOwnProperty.call(QUERIES, name)
    ? QUERIES[name] : null;
  if (!f) {
    log.debug("Leaving build(). Unknown.");
    throw new Error('directory_queries: no query called ' + String(name));
  }
  log.debug("Leaving build().");
  return f.apply(null, Array.isArray(args) ? args : []);
}

module.exports = {
  COLUMNS: COLUMNS,
  MAX_PAGE: MAX_PAGE,
  QUERIES: QUERIES,
  build: build,
  answerOf: answerOf,
  rowOf: rowOf,
  byKeys: byKeys,
  byName: byName,
  byUuid: byUuid,
  byMail: byMail,
  byAttribute: byAttribute,
  page: page,
  count: count,
  hasChild: hasChild,
  withAttribute: withAttribute,
  anyWithAttribute: anyWithAttribute,
  classesUnder: classesUnder,
  namesUnder: namesUnder,
  residentOnly: residentOnly
};
