// SPDX-FileCopyrightText: 2026 Iya CyberSecurity Solutions, LLC
// SPDX-License-Identifier: BUSL-1.1

//! Turns `tables/error_codes.json` — the export of `common/error_codes.js`
//! that `tests/tools/export-rust-tables.js` writes — into a constant per
//! code and the table `sts_core::errors` describes them with. A code that
//! is not in the table is a name that does not exist, so it does not
//! compile; a RETIRED code is a deprecated constant, so a new use of one is
//! a warning the workspace's CI treats as an error.

use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

fn text<'a>(value: &'a serde_json::Value, key: &str) -> &'a str {
    value.get(key).and_then(|v| v.as_str()).unwrap_or("")
}

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo::rerun-if-changed=tables/error_codes.json");
    let source = fs::read_to_string("tables/error_codes.json")?;
    let table: serde_json::Value = serde_json::from_str(&source)?;
    let empty = Vec::new();
    let codes = table
        .get("codes")
        .and_then(|c| c.as_array())
        .unwrap_or(&empty);
    let subsystems = table
        .get("subsystems")
        .and_then(|c| c.as_array())
        .unwrap_or(&empty);
    if codes.is_empty() || subsystems.is_empty() {
        return Err("tables/error_codes.json holds no codes".into());
    }

    let mut out = String::new();
    writeln!(out, "// Generated by build.rs from tables/error_codes.json.")?;
    for row in codes {
        let code = text(row, "code");
        let name = code.replace('-', "_");
        if row.get("retired").and_then(|r| r.as_bool()) == Some(true) {
            writeln!(
                out,
                "#[deprecated(note = \"retired: the condition no longer \
                 exists\")]"
            )?;
        }
        writeln!(
            out,
            "pub const {}: ErrorCode = ErrorCode({:?});",
            name, code
        )?;
    }
    writeln!(out, "pub(crate) static ROWS: &[Row] = &[")?;
    for row in codes {
        writeln!(
            out,
            "    Row {{ code: {:?}, summary: {:?}, spec: {:?}, \
             retired: {} }},",
            text(row, "code"),
            text(row, "summary"),
            text(row, "spec"),
            row.get("retired").and_then(|r| r.as_bool()) == Some(true)
        )?;
    }
    writeln!(out, "];")?;
    writeln!(out, "pub(crate) static SUBSYSTEMS: &[Subsystem] = &[")?;
    for one in subsystems {
        writeln!(
            out,
            "    Subsystem {{ id: {:?}, label: {:?}, location: {:?}, \
             what: {:?} }},",
            text(one, "id"),
            text(one, "label"),
            text(one, "where"),
            text(one, "what")
        )?;
    }
    writeln!(out, "];")?;

    let dir = std::env::var("OUT_DIR")?;
    fs::write(Path::new(&dir).join("error_codes.rs"), out)?;
    Ok(())
}
