'use strict';
//
// File: pki_authoring.ts
//
// ===========================================================================
// THE CERTIFICATE & KEY CONFIGURATION PANE, AS A MODEL.
//
// `common/pki.js` builds this service's certificate authority and issues the
// FIXED kinds of leaf this service needs from it — signing key pairs for RFC
// 7521 and RFC 7523, TLS certificates, enrolled certificates — each to a
// profile it decides. This file is the other half: **an arbitrary
// certificate, with every field and every extension exposed**, issued from
// any authority whose private key is here.
//
// ---------------------------------------------------------------------------
// IT IS MODELLED ON THE PARENT PROJECT'S *PKI / X.509* PAGE AND IS NOT A COPY
// OF IT, AND THE DIFFERENCE DECIDES THE SHAPE OF EVERYTHING BELOW.
//
// That page is `client/public/pki.html` over `client/src/pki.js`: Web Crypto
// and pkijs IN THE BROWSER, twenty-two extension cards, live filtering as the
// profile and the cryptographic approach change. Its whole claim is that the
// key never leaves the browser.
//
// **This console is `script-src 'none'`** (every page of it but
// `/admin/api-explorer`), and this service's claim is the opposite one: the
// private keys of a certificate authority belong in the process that signs.
// So the MODEL is mirrored exactly — the same fourteen profiles, the same
// five cryptographic approaches, the same twenty-two extensions, the same
// four keystore formats, out of the same encoder — and every computation that
// page does in a browser is done here instead:
//
// | On that page | Here |
// |---|---|
// | `onProfileChange()` rewrites the extension checkboxes | *Apply the profile* is a SUBMIT, and the form comes back rewritten |
// | `onPqModeChange()` filters the Key Algorithm menu | the same submit; and an impossible pair is refused by name at the issue |
// | `onIssuerChange()` narrows Signature Algorithm | the same submit |
// | `newSerial()` refills the serial after an issue | the redrawn form carries a fresh one |
// | the JWK toggle converts the two key fields | a checkbox the redraw honours, converted through the same module |
// | the Copy buttons | gone: there is no script to copy with, and a textarea selects |
// | `downloadKeys()` builds a Blob | `POST /admin/pki/export` answers with the FILE |
//
// **THE FORM IS THE STATE AND THERE IS NO DRAFT STORE.** Every field is
// re-posted by every button, so *Apply the profile* is a pure function of what
// was on the screen — which is what lets the pane work across the request
// worker pool with no affinity and leaves this service with no fourth place a
// half-finished certificate could be sitting.
//
// **THE FIELD NAMES ARE THAT PAGE'S, VERBATIM** — `pki_dn_cn`, `pki_ext_bc`,
// `pki_ku_keyCertSign`. Not decoration: the two pages are one form over one
// encoder, and a reader moving between them should be able to see that. It is
// also what makes `FIELDS` below checkable — `tests/pki_authoring.js` asserts
// that the console draws every name in it and parses every name it draws.
//
// ---------------------------------------------------------------------------
// WHAT THIS FILE OWNS AND WHAT IT DOES NOT.
//
// It owns the READING of a form: the six line-grammars, the subject, the
// extension set, the profile defaults, which algorithms an approach allows,
// and what an issue does with all of it. It owns NO STORE — the objects live
// in `pki.js`'s `pki:<realm>` keystore row, for the argument that file makes
// about there being one answer to *where does this service keep a private
// key* — and it draws NO HTML, which is `admin-ui/pki_admin.ts`'s.
//
// A LIBRARY (rule 3): it registers no route, so its position in the require
// order is not a position. It requires `config`, `pki`, `error_codes` and the
// two vendored PKI modules; none of them requires it back, so it cannot close
// a cycle.
//
// ---------------------------------------------------------------------------
// ONE COST IS REAL AND IS SAID OUT LOUD RATHER THAN DISCOVERED.
//
// Generating a post-quantum key pair is SLOW and it runs on this thread.
// `common/worker_pool.js` exists precisely because an SLH-DSA operation stops
// this process for seconds, and this file deliberately does not use it: that
// pool's job table runs `common/pq_jose.js`, which is this service's OWN
// reading of the post-quantum constructions and is deliberately independent of
// the vendored one (`pq_jose.js`'s header spends a page on why). Handing a
// key generated by one to a certificate encoder that expects the other's byte
// layout is exactly the class of defect the independence exists to expose, and
// it would be introduced here to save a console button a few seconds.
//
// So the slow algorithms are slow, and `SLOW_FAMILIES` is what the page warns
// with. In `dispatch` mode the console holds affinity to a REQUEST worker, so
// the stall is that worker's rather than the listener's — which is a genuine
// mitigation and is also not a reason to pretend the cost is gone.
//
// ---------------------------------------------------------------------------
// TYPESCRIPT, AS A CLASS (#50, 2026-09-16). `PkiAuthoring` takes the logger,
// `config`, `pki`, `error_codes`, node's `crypto` and the two vendored PKI
// modules through its constructor, as `PkiAuthoringDeps`; every function this
// file had is a method of it, and the small helpers (`textOf()`, `flagOf()`,
// `asShown()` and the rest nobody outside called) are private. The TABLES —
// `FIELDS`, `DN_FIELDS`, `PQ_MODES` and their derivatives — stay module-level
// constants built at load, exactly as before, because `FIELDS` is generated
// from the encoder's own tables at that moment; the class carries them as
// static members too. The module still exports every name it did, for
// `admin-ui/pki_admin.ts`, `mgmt-api/` and the tests. Since #50's R2 the
// composition root builds the instance (`PkiAuthoring.defaultDeps()`) and
// installs it; the module's old export names are FACADES that forward to it,
// for the JavaScript callers, and a process without the root builds a default
// when this module finishes loading.
// ===========================================================================

import bunyan = require('bunyan');
import nodeCrypto = require('crypto');
import config = require('./config');

const log = bunyan.createLogger({
  name: 'pki_authoring',
  level: config.value('global.logLevel')
});

import pki = require('./pki');
// The error-code registry (a leaf). A grammar refusal is thrown with its code
// marked non-enumerably on the Error, so `issue()` can say WHICH grammar; a
// refusal returned to a caller carries its code the same way.
import errorCodes = require('./error_codes');
// The debugger's own PKI code, byte-identical. DO NOT EDIT THEM HERE — see
// `common/vendored/CLAUDE.md`. One encoder for this page and for that
// project's, which is the whole point of vendoring them.
import x509 = require('./vendored/x509');
import keyMaterial = require('./vendored/key_material');
import InstanceSlot = require('./instance_slot');

// ---------------------------------------------------------------------------
// THE FIVE CRYPTOGRAPHIC APPROACHES.
//
// They are not variations on one idea; they are three different answers to
// "what do I do about a validator that has never heard of ML-DSA", plus the
// two that do not ask the question. Which is right depends on who has to READ
// the certificate, so it is a control rather than a default — the prose is the
// parent page's own, because the two pages must not come to say different
// things about one decision.
// ---------------------------------------------------------------------------
const PQ_MODES = [
  { id: 'any', label: 'Any — show every algorithm', classical: true,
    families: ['ML-DSA', 'SLH-DSA', 'Composite ML-DSA', 'ML-KEM'],
    note: 'Every algorithm this build has. The three post-quantum families ' +
          'and the classical ones are listed together; pick one of the other ' +
          'approaches to narrow the list and read what it means.' },
  { id: 'classical', label: 'Classical only (RSA, ECDSA, EdDSA)',
    classical: true, families: [],
    note: 'RSA, ECDSA and Ed25519 — what a certificate has carried since ' +
          'RFC 5280. Nothing here resists a quantum adversary, which is the ' +
          'whole reason the other three exist.' },
  { id: 'pure', label: 'Pure post-quantum (ML-DSA, SLH-DSA, ML-KEM)',
    classical: false, families: ['ML-DSA', 'SLH-DSA', 'ML-KEM'],
    note: 'One key and one signature, both post-quantum: ML-DSA (RFC 9881), ' +
          'SLH-DSA (RFC 9909) and, as a subject key only, ML-KEM (RFC 9935). ' +
          'These are published standards and OpenSSL 3.5 reads them — and ' +
          'anything older refuses the certificate outright, which is the ' +
          'trade this approach makes.' },
  { id: 'composite', label: 'Composite (one OID, two signatures)',
    classical: false, families: ['Composite ML-DSA'],
    note: 'One OID naming an ML-DSA key AND a traditional key, with two ' +
          'signatures concatenated inside the one signatureValue ' +
          '(draft-ietf-lamps-pq-composite-sigs-19). A verifier either checks ' +
          'both halves or understands neither, which is what makes it a ' +
          'single algorithm rather than a pair. STILL A DRAFT: no released ' +
          'OpenSSL implements it, so certificates issued here are test ' +
          'artifacts.' },
  { id: 'hybrid', label: 'Hybrid (alternative-signature extensions)',
    classical: true, families: [],
    note: 'A second key and a second signature carried in three NON-CRITICAL ' +
          'extensions — subjectAltPublicKeyInfo (2.5.29.72), ' +
          'altSignatureAlgorithm (2.5.29.73) and altSignatureValue ' +
          '(2.5.29.74), ITU-T X.509 (2019) clause 9.8 — so a validator that ' +
          'has never heard of them sees an ordinary classical certificate ' +
          'and accepts it, which is the entire point. The alternative ' +
          'signature covers the preTBSCertificate and NOT the whole ' +
          'TBSCertificate; getting that wrong produces a signature that ' +
          'verifies nowhere.' }
];

const PQ_MODE_IDS = PQ_MODES.map(function (one) {
  return one.id;
});

// The families whose key generation is measured in SECONDS rather than
// milliseconds, named so the page can warn before the button is pressed
// rather than after. See the cost note in the header.
const SLOW_FAMILIES = ['SLH-DSA'];

// ---------------------------------------------------------------------------
// EVERY FIELD ON THE PANE, IN ONE TABLE.
//
// The page draws from it, `draftFrom()` reads from it, and
// `tests/pki_authoring.js` checks the two against each other — so a field
// added to the form and not to the parser, or parsed and never drawn, is a
// test failure rather than a control that silently does nothing. That is the
// same argument `sts_metadata.js` makes about endpoints, one layer down.
//
// `kind` decides how a posted value is read and nothing else:
//   text   a string, trimmed
//   lines  a textarea read as lines (blank and `#` lines dropped by the parsers)
//   flag   a checkbox: PRESENT means true, because an unticked box posts nothing
//   raw    a string kept exactly as posted (the key fields — PEM has meaningful
//          line breaks and a trim would not hurt, but a strip might)
// ---------------------------------------------------------------------------
const FIELDS: FieldSpec[] = [
  // --- Issue a Certificate -------------------------------------------------
  { name: 'pki_profile', kind: 'text', dflt: '' },
  { name: 'pki_issuer', kind: 'text', dflt: '' },
  { name: 'pki_pq_mode', kind: 'text', dflt: 'any' },
  { name: 'pki_sig_alg', kind: 'text', dflt: '' },
  { name: 'pki_serial', kind: 'text', dflt: '' },
  { name: 'pki_validity_years', kind: 'text', dflt: '' },
  { name: 'pki_not_before', kind: 'text', dflt: '' },
  { name: 'pki_not_after', kind: 'text', dflt: '' },
  // --- Key Pair ------------------------------------------------------------
  { name: 'pki_key_alg', kind: 'text', dflt: '' },
  { name: 'pki_key_jwk', kind: 'flag', dflt: false },
  { name: 'pki_reuse_key', kind: 'flag', dflt: false },
  { name: 'pki_private_key', kind: 'raw', dflt: '' },
  { name: 'pki_public_key', kind: 'raw', dflt: '' },
  { name: 'pki_gen_csr', kind: 'flag', dflt: false },
  // **THE ONE FIELD ON THIS PANE THAT MEANS SOMETHING DIFFERENT FROM THE
  // PAGE IT IS MODELLED ON, AND IT IS KEPT RATHER THAN DROPPED.** There it is
  // "save private keys here" and decides whether the browser writes them to
  // localStorage. There is no browser store here — the keys are in this
  // realm's keystore row — so it decides whether the ISSUED OBJECT keeps its
  // private half at all. Cleared, the certificate and the public key are
  // stored and the private key is discarded as the reply is written: the
  // object can be inspected and used as a trust anchor, and can never sign
  // again or be exported. That is the same OBSERVABLE behaviour the debugger's
  // checkbox produces, which is why it keeps the field rather than losing it
  // to a difference in where the store is.
  { name: 'pki_save_keys', kind: 'flag', dflt: true },
  { name: 'pki_csr', kind: 'raw', dflt: '' },
  { name: 'pki_alt_key_alg', kind: 'text', dflt: '' },
  { name: 'pki_alt_reuse_key', kind: 'flag', dflt: false },
  { name: 'pki_alt_private_key', kind: 'raw', dflt: '' },
  { name: 'pki_alt_public_key', kind: 'raw', dflt: '' },
  // --- Export --------------------------------------------------------------
  { name: 'pki_ks_format', kind: 'text', dflt: 'pem' },
  { name: 'pki_ks_password', kind: 'text', dflt: '' },
  { name: 'pki_ks_include_chain', kind: 'flag', dflt: true },
  // --- Subject Distinguished Name -----------------------------------------
  { name: 'pki_dn_cn', kind: 'text', dflt: '' },
  { name: 'pki_dn_o', kind: 'text', dflt: '' },
  { name: 'pki_dn_ou', kind: 'text', dflt: '' },
  { name: 'pki_dn_l', kind: 'text', dflt: '' },
  { name: 'pki_dn_st', kind: 'text', dflt: '' },
  { name: 'pki_dn_c', kind: 'text', dflt: '' },
  { name: 'pki_dn_email', kind: 'text', dflt: '' },
  { name: 'pki_dn_dc', kind: 'text', dflt: '' },
  { name: 'pki_dn_uid', kind: 'text', dflt: '' },
  { name: 'pki_dn_serialnumber', kind: 'text', dflt: '' },
  { name: 'pki_dn_extra', kind: 'lines', dflt: '' },
  // --- X.509v3 extensions --------------------------------------------------
  { name: 'pki_ext_bc', kind: 'flag', dflt: false },
  { name: 'pki_bc_ca', kind: 'flag', dflt: false },
  { name: 'pki_bc_pathlen', kind: 'text', dflt: '' },
  { name: 'pki_bc_critical', kind: 'flag', dflt: false },
  { name: 'pki_ext_ku', kind: 'flag', dflt: false },
  { name: 'pki_ku_critical', kind: 'flag', dflt: false },
  { name: 'pki_ext_eku', kind: 'flag', dflt: false },
  { name: 'pki_eku_critical', kind: 'flag', dflt: false },
  { name: 'pki_eku_extra', kind: 'lines', dflt: '' },
  { name: 'pki_ext_skid', kind: 'flag', dflt: false },
  { name: 'pki_ext_akid', kind: 'flag', dflt: false },
  { name: 'pki_akid_issuer_serial', kind: 'flag', dflt: false },
  { name: 'pki_ext_san', kind: 'flag', dflt: false },
  { name: 'pki_san', kind: 'lines', dflt: '' },
  { name: 'pki_san_critical', kind: 'flag', dflt: false },
  { name: 'pki_ext_ian', kind: 'flag', dflt: false },
  { name: 'pki_ian', kind: 'lines', dflt: '' },
  { name: 'pki_ian_critical', kind: 'flag', dflt: false },
  { name: 'pki_ext_cdp', kind: 'flag', dflt: false },
  { name: 'pki_cdp', kind: 'lines', dflt: '' },
  { name: 'pki_cdp_critical', kind: 'flag', dflt: false },
  { name: 'pki_ext_freshest', kind: 'flag', dflt: false },
  { name: 'pki_freshest', kind: 'lines', dflt: '' },
  { name: 'pki_ext_aia', kind: 'flag', dflt: false },
  { name: 'pki_aia', kind: 'lines', dflt: '' },
  { name: 'pki_ext_sia', kind: 'flag', dflt: false },
  { name: 'pki_sia', kind: 'lines', dflt: '' },
  { name: 'pki_ext_policies', kind: 'flag', dflt: false },
  { name: 'pki_policies', kind: 'lines', dflt: '' },
  { name: 'pki_policies_critical', kind: 'flag', dflt: false },
  { name: 'pki_ext_policy_mappings', kind: 'flag', dflt: false },
  { name: 'pki_policy_mappings', kind: 'lines', dflt: '' },
  { name: 'pki_ext_policy_constraints', kind: 'flag', dflt: false },
  { name: 'pki_require_explicit_policy', kind: 'text', dflt: '' },
  { name: 'pki_inhibit_policy_mapping', kind: 'text', dflt: '' },
  { name: 'pki_ext_name_constraints', kind: 'flag', dflt: false },
  { name: 'pki_name_constraints', kind: 'lines', dflt: '' },
  { name: 'pki_nc_critical', kind: 'flag', dflt: false },
  { name: 'pki_ext_inhibit_any', kind: 'flag', dflt: false },
  { name: 'pki_inhibit_any_skip', kind: 'text', dflt: '' },
  { name: 'pki_ext_pkup', kind: 'flag', dflt: false },
  { name: 'pki_pkup_not_before', kind: 'text', dflt: '' },
  { name: 'pki_pkup_not_after', kind: 'text', dflt: '' },
  { name: 'pki_ext_tls_feature', kind: 'flag', dflt: false },
  { name: 'pki_tls_feature', kind: 'lines', dflt: '' },
  { name: 'pki_ext_ocsp_nocheck', kind: 'flag', dflt: false },
  { name: 'pki_ext_ns_cert_type', kind: 'flag', dflt: false },
  { name: 'pki_ext_ns_comment', kind: 'flag', dflt: false },
  { name: 'pki_ns_comment', kind: 'text', dflt: '' },
  { name: 'pki_custom_extensions', kind: 'lines', dflt: '' },
  // The store's selection, which is a field on this form rather than a second
  // one: *Use this key pair*, *Export* and *Remove* all act on it, and a
  // selection held anywhere but in the form would be state this pane
  // deliberately does not keep (see THE FORM IS THE STATE above).
  { name: 'pki_selected', kind: 'text', dflt: '' }
]
  // The nine keyUsage bits, the sixteen extendedKeyUsage purposes and the five
  // Netscape ones are GENERATED from the encoder's own tables rather than
  // written out, which is `crypto_metadata.js`'s rule applied to a form: a bit
  // the encoder gains appears on this page the day it is added, and a checkbox
  // for a bit the encoder does not have cannot exist.
  .concat(x509.KEY_USAGE_BITS.map(function (bit) {
    return { name: 'pki_ku_' + bit.name, kind: 'flag', dflt: false };
  }))
  .concat(Object.keys(x509.EKU_OIDS).map(function (name) {
    return { name: 'pki_eku_' + name, kind: 'flag', dflt: false };
  }))
  .concat(x509.NS_CERT_TYPE_BITS.map(function (bit) {
    return { name: 'pki_ns_' + bit.name, kind: 'flag', dflt: false };
  }));

const FIELD_NAMES = FIELDS.map(function (one) {
  return one.name;
});

// The subject DN's named boxes, in the order they are ENCODED. A Name is an
// ordered RDNSequence and a reordered DN is a different name that chains to
// nothing, so this order is part of what the pane means rather than a layout
// choice.
const DN_FIELDS = [
  { attr: 'CN', field: 'pki_dn_cn' },
  { attr: 'O', field: 'pki_dn_o' },
  { attr: 'OU', field: 'pki_dn_ou' },
  { attr: 'L', field: 'pki_dn_l' },
  { attr: 'ST', field: 'pki_dn_st' },
  { attr: 'C', field: 'pki_dn_c' },
  { attr: 'emailAddress', field: 'pki_dn_email' },
  { attr: 'DC', field: 'pki_dn_dc' },
  { attr: 'UID', field: 'pki_dn_uid' },
  { attr: 'serialNumber', field: 'pki_dn_serialnumber' }
];

// The alternative-name types the line grammar below accepts, and the name the
// encoder knows each by. `othername` is read separately, because it carries an
// OID as well as a value.
const GENERAL_NAME_KINDS: Record<string, string> = {
  dns: 'dns', ip: 'ip', email: 'email', uri: 'uri', upn: 'upn',
  krb5: 'krb5', rid: 'registeredID', dirname: 'dirName'
};

// One field of the pane: how a posted value is read, and what it is when
// nothing was posted.
interface FieldSpec {
  name: string;
  kind: string;
  dflt: string | boolean;
}

// A draft is the form: every field name to its value.
type Draft = Record<string, any>;

// A refusal or an answer, in the shape every action here returns.
type Outcome = Record<string, any>;

interface Logger {
  debug(message: string): void;
  info(message: string): void;
  warn(message: string): void;
  error(message: string): void;
}

// What the pane needs from the rest of the service. The vendored modules and
// `pki.js` are JavaScript, and are described by their own module types.
interface PkiAuthoringDeps {
  log: Logger;
  config: { value(key: string): any };
  pki: typeof pki;
  errorCodes: typeof errorCodes;
  x509: typeof x509;
  keyMaterial: typeof keyMaterial;
  nodeCrypto: typeof nodeCrypto;
}

class PkiAuthoring {
  static readonly FIELDS = FIELDS;
  static readonly FIELD_NAMES = FIELD_NAMES;
  static readonly DN_FIELDS = DN_FIELDS;
  static readonly PQ_MODES = PQ_MODES;
  static readonly PQ_MODE_IDS = PQ_MODE_IDS;
  static readonly SLOW_FAMILIES = SLOW_FAMILIES;

  constructor(private readonly deps: PkiAuthoringDeps) {
    deps.log.debug("Entering PkiAuthoring.constructor().");
    deps.log.debug("Leaving PkiAuthoring.constructor().");
  }

  // What the composition root passes: the modules the load-time instance
  // was built from before R2.
  static defaultDeps(): PkiAuthoringDeps {
    log.debug("Entering PkiAuthoring.defaultDeps().");
    log.debug("Leaving PkiAuthoring.defaultDeps().");
    return {
      log: log,
      config: config,
      pki: pki,
      errorCodes: errorCodes,
      x509: x509,
      keyMaterial: keyMaterial,
      nodeCrypto: nodeCrypto
    };
  }

  // ---------------------------------------------------------------------------
  // READING A POSTED FORM.
  // ---------------------------------------------------------------------------

  // A posted body into a draft that has every field in it, whatever the browser
  // sent. An unticked checkbox posts NOTHING, so a flag is present-or-absent
  // and never a value — which is also why `defaultDraft()` below cannot simply
  // be this function over an empty object.
  draftFrom(body: Record<string, unknown> | null | undefined): Draft {
    const { log } = this.deps;
    log.debug('Entering PkiAuthoring.draftFrom().');
    const posted: Record<string, any> = body || {};
    const out: Draft = {};
    FIELDS.forEach(function (field) {
      const raw = posted[field.name];
      if (field.kind === 'flag') {
        // **A REAL BOOLEAN IS TAKEN AT ITS WORD, AND THAT IS NOT A NICETY.**
        // Every pane action answers with the whole `draft`, whose flags are
        // JSON booleans — and the contract this API states is "post back what
        // came back". Without this line a `false` is not a browser's absent
        // checkbox and not one of the two words below, so it read as TRUE:
        // `apply-profile` then `issue-certificate` with the draft in between
        // turned every cleared box ON, and the first thing that produced was
        // "reuse the key pair below is ticked and the boxes are empty" about a
        // caller that never ticked it. `tests/vendored/sts_pki_workbench.js`
        // found it on its first run.
        if (typeof raw === 'boolean') {
          out[field.name] = raw;
          return;
        }
        // A browser's checkbox is PRESENT or ABSENT and carries no false value,
        // so presence is the reading — with the two words a JSON caller may
        // reasonably send for OFF excluded, since `"false"` meaning true is the
        // kind of thing nobody finds until a certificate carries an extension
        // nobody asked for.
        out[field.name] = raw !== undefined && raw !== null && raw !== '' &&
                          raw !== '0' && raw !== 'false';
        return;
      }
      if (raw === undefined || raw === null) {
        out[field.name] = field.dflt;
        return;
      }
      // A repeated field arrives as an array from `bodyValues()`-shaped parsers
      // and as a last-one-wins string from `parseBody()`. Neither shape belongs
      // on this form, so the first value is taken rather than a stringified
      // array being written into a certificate.
      const value = Array.isArray(raw) ? String(raw[0] || '') : String(raw);
      out[field.name] = field.kind === 'raw' ? value : value.trim();
    });
    log.debug('Leaving PkiAuthoring.draftFrom().');
    return out;
  }

  private textOf(draft: Draft | null | undefined, name: string): string {
    const { log } = this.deps;
    log.debug("Entering PkiAuthoring.textOf().");
    log.debug("Leaving PkiAuthoring.textOf().");
    return String((draft && draft[name]) || '').trim();
  }

  private flagOf(draft: Draft | null | undefined, name: string): boolean {
    const { log } = this.deps;
    log.debug("Entering PkiAuthoring.flagOf().");
    log.debug("Leaving PkiAuthoring.flagOf().");
    return !!(draft && draft[name]);
  }

  // A textarea as a list of lines, with blanks and comments dropped. Every line
  // grammar below starts here, so `#` is a comment everywhere on this pane
  // rather than in some of the boxes.
  linesOf(draft: Draft | null | undefined, name: string): string[] {
    const { log } = this.deps;
    log.debug("Entering PkiAuthoring.linesOf().");
    log.debug("Leaving PkiAuthoring.linesOf().");
    return String((draft && draft[name]) || '').split(/\r?\n/)
      .map(function (line) {
        return line.trim();
      })
      .filter(function (line) {
        return line && line.charAt(0) !== '#';
      });
  }

  // ---------------------------------------------------------------------------
  // THE SIX LINE GRAMMARS. Each is the parent page's, and each THROWS with the
  // grammar in the message rather than dropping a line it cannot read — a
  // certificate quietly missing the name somebody typed is the worst outcome
  // available here, because it verifies.
  // ---------------------------------------------------------------------------

  parseAltNames(lines: string[]) {
    const { log, errorCodes } = this.deps;
    log.debug('Entering PkiAuthoring.parseAltNames().');
    const out = [];
    lines.forEach(function (line) {
      const colon = line.indexOf(':');
      if (colon < 0) {
        throw errorCodes.mark(new Error('Alternative name "' + line + '" has ' +
                        'no type. Write dns:example.com, ip:10.0.0.1, ' +
                        'email:a@b, uri:https://…, upn:user@REALM, ' +
                        'krb5:host/x@REALM, rid:1.2.3.4, dirname:CN=x, or ' +
                        'othername:<oid>:<base64 DER>.'), 'STS-PKI-0078');
      }
      const kind = line.slice(0, colon).trim().toLowerCase();
      const value = line.slice(colon + 1).trim();
      if (kind === 'othername') {
        const second = value.indexOf(':');
        if (second < 0) {
          throw errorCodes.mark(new Error('othername needs an OID and a ' +
                                          'base64 DER value: ' +
                                          'othername:1.2.3.4:BASE64'),
                                'STS-PKI-0078');
        }
        out.push({ kind: 'otherName', oid: value.slice(0, second).trim(),
                   value: value.slice(second + 1).trim() });
        return;
      }
      if (!GENERAL_NAME_KINDS[kind]) {
        throw errorCodes.mark(new Error('Unknown alternative name type "' +
                        kind + '". ' +
                        'The types ' +
                        'are ' + Object.keys(GENERAL_NAME_KINDS).join(', ') +
                        ' and othername.'), 'STS-PKI-0078');
      }
      out.push({ kind: GENERAL_NAME_KINDS[kind], value: value });
    });
    log.debug('Leaving PkiAuthoring.parseAltNames(). ' +
              out.length + ' name(s).');
    return out;
  }

  // ocsp:http://… | caissuers:http://… | <oid>:http://…
  parseAccessDescriptions(lines: string[]) {
    const { log, errorCodes } = this.deps;
    log.debug('Entering PkiAuthoring.parseAccessDescriptions().');
    const known: Record<string, string> = {
      ocsp: 'ocsp', caissuers: 'caIssuers',
      timestamping: 'timeStamping', carepository: 'caRepository'
    };
    const out = [];
    lines.forEach(function (line) {
      const colon = line.indexOf(':');
      if (colon < 0) {
        throw errorCodes.mark(new Error('Access description "' + line +
                        '" has no method. Write ocsp:http://… or ' +
                        'caissuers:http://… ' +
                        '— or <oid>:<url> for a method this page does not ' +
                        'name.'), 'STS-PKI-0079');
      }
      const method = line.slice(0, colon).trim();
      out.push({ method: known[method.toLowerCase()] || method,
                 url: line.slice(colon + 1).trim() });
    });
    log.debug('Leaving PkiAuthoring.parseAccessDescriptions(). ' + out.length +
              ' entry(ies).');
    return out;
  }

  // <policy oid>[|cps=<uri>][|notice=<text>]
  parsePolicies(lines: string[]) {
    const { log } = this.deps;
    log.debug('Entering PkiAuthoring.parsePolicies().');
    const out = [];
    lines.forEach(function (line) {
      const parts = line.split('|');
      const policy: { oid: string; cps?: string; notice?: string } = {
        oid: parts[0].trim()
      };
      for (let i = 1; i < parts.length; i++) {
        const piece = parts[i].trim();
        const eq = piece.indexOf('=');
        if (eq < 0) {
          continue;
        }
        const name = piece.slice(0, eq).trim().toLowerCase();
        const value = piece.slice(eq + 1).trim();
        if (name === 'cps') {
          policy.cps = value;
        } else if (name === 'notice') {
          policy.notice = value;
        }
      }
      out.push(policy);
    });
    log.debug('Leaving PkiAuthoring.parsePolicies(). ' +
              out.length + ' policy(ies).');
    return out;
  }

  // <issuer policy oid>=<subject policy oid>
  parsePolicyMappings(lines: string[]) {
    const { log, errorCodes } = this.deps;
    log.debug('Entering PkiAuthoring.parsePolicyMappings().');
    const out = [];
    lines.forEach(function (line) {
      const eq = line.indexOf('=');
      if (eq < 0) {
        throw errorCodes.mark(new Error('A policy mapping is <issuer ' +
                                        'oid>=<subject oid>; got "' +
                        line + '".'), 'STS-PKI-0080');
      }
      out.push({ issuer: line.slice(0, eq).trim(),
                 subject: line.slice(eq + 1).trim() });
    });
    log.debug('Leaving PkiAuthoring.parsePolicyMappings(). ' +
              out.length + ' mapping(s).');
    return out;
  }

  // permit dns:example.com | exclude ip:10.0.0.0/8
  //
  // The IP form takes a PREFIX: a name constraint's iPAddress is the address
  // FOLLOWED BY ITS MASK — eight bytes for v4, not four — which is the one
  // place a general name is not simply an address, and the encoder handles it.
  parseNameConstraints(lines: string[]) {
    const self = this;
    const { log, errorCodes } = this.deps;
    log.debug('Entering PkiAuthoring.parseNameConstraints().');
    const out = { permitted: [], excluded: [] };
    lines.forEach(function (line) {
      const space = line.indexOf(' ');
      if (space < 0) {
        throw errorCodes.mark(new Error('A name constraint is ' +
                        '"permit <name>" or "exclude <name>"; got ' +
                        '"' + line + '".'), 'STS-PKI-0081');
      }
      const verb = line.slice(0, space).trim().toLowerCase();
      const names = self.parseAltNames([line.slice(space + 1).trim()]);
      if (verb === 'permit' || verb === 'permitted') {
        out.permitted = out.permitted.concat(names);
      } else if (verb === 'exclude' || verb === 'excluded') {
        out.excluded = out.excluded.concat(names);
      } else {
        throw errorCodes.mark(new Error('A name constraint starts with ' +
                        '"permit" or "exclude"; got ' +
                        '"' + verb + '".'), 'STS-PKI-0081');
      }
    });
    log.debug('Leaving PkiAuthoring.parseNameConstraints(). ' +
              out.permitted.length +
              ' permitted, ' + out.excluded.length + ' excluded.');
    return out;
  }

  // <oid>|<critical or ->|<base64 DER of the extension value>
  parseCustomExtensions(lines: string[]) {
    const { log, errorCodes } = this.deps;
    log.debug('Entering PkiAuthoring.parseCustomExtensions().');
    const out = [];
    lines.forEach(function (line) {
      const parts = line.split('|');
      if (parts.length < 3) {
        throw errorCodes.mark(new Error('A custom extension is ' +
                        '<oid>|<critical or ->|<base64 DER>; got ' +
                        '"' + line + '".'), 'STS-PKI-0082');
      }
      out.push({ oid: parts[0].trim(),
                 critical: /^crit/i.test(parts[1].trim()),
                 // Joined back rather than taken as parts[2]: base64 has no `|`
                 // in it, but a value somebody pasted with one would otherwise
                 // be silently truncated at it.
                 value: parts.slice(2).join('|').trim() });
    });
    log.debug('Leaving PkiAuthoring.parseCustomExtensions(). ' +
              out.length + ' of them.');
    return out;
  }

  // ---------------------------------------------------------------------------
  // THE SUBJECT. The named boxes in encoding order, then the extra lines in the
  // order they were written — `NAME=value` where the encoder knows the name,
  // and `OID=value` where it does not, which is what lets a DN carry an
  // attribute this page has never heard of.
  // ---------------------------------------------------------------------------
  subjectFrom(draft: Draft) {
    const self = this;
    const { log, errorCodes, x509 } = this.deps;
    log.debug('Entering PkiAuthoring.subjectFrom().');
    const out = [];
    DN_FIELDS.forEach(function (field) {
      const value = self.textOf(draft, field.field);
      if (value) {
        out.push({ name: field.attr, value: value });
      }
    });
    self.linesOf(draft, 'pki_dn_extra').forEach(function (line) {
      const eq = line.indexOf('=');
      if (eq < 0) {
        throw errorCodes.mark(new Error('An extra subject attribute is ' +
                        'NAME=value or OID=value; got ' +
                        '"' + line + '".'), 'STS-PKI-0083');
      }
      const name = line.slice(0, eq).trim();
      const value = line.slice(eq + 1).trim();
      if (x509.DN_ATTRS[name]) {
        out.push({ name: name, value: value });
      } else {
        out.push({ oid: name, value: value });
      }
    });
    log.debug('Leaving PkiAuthoring.subjectFrom(). ' +
              out.length + ' attribute(s).');
    return out;
  }

  // ---------------------------------------------------------------------------
  // THE EXTENSION SET, in the shape `x509.issueCertificate()` takes. ONE
  // function, so a test can check the form against the encoder in one call —
  // which is the parent page's reason for `collectExtensions()` and holds here
  // for the same reason.
  // ---------------------------------------------------------------------------
  extensionsFrom(draft: Draft) {
    const self = this;
    const { log, x509 } = this.deps;
    log.debug('Entering PkiAuthoring.extensionsFrom().');
    const ticked = function (prefix, names) {
      log.debug("Entering ticked().");
      log.debug("Leaving ticked().");
      return names.filter(function (name) {
        return self.flagOf(draft, prefix + name);
      });
    };
    const constraints = self.parseNameConstraints(self.linesOf(draft,
                                                     'pki_name_constraints'));
    const ext = {
      basicConstraints: {
        present: self.flagOf(draft, 'pki_ext_bc'),
        ca: self.flagOf(draft, 'pki_bc_ca'),
        pathLen: self.textOf(draft, 'pki_bc_pathlen'),
        critical: self.flagOf(draft, 'pki_bc_critical')
      },
      keyUsage: {
        present: self.flagOf(draft, 'pki_ext_ku'),
        usages: ticked('pki_ku_', x509.KEY_USAGE_BITS.map(function (bit) {
          return bit.name;
        })),
        critical: self.flagOf(draft, 'pki_ku_critical')
      },
      extKeyUsage: {
        present: self.flagOf(draft, 'pki_ext_eku'),
        usages: ticked('pki_eku_', Object.keys(x509.EKU_OIDS))
          .concat(self.linesOf(draft, 'pki_eku_extra')),
        critical: self.flagOf(draft, 'pki_eku_critical')
      },
      subjectKeyIdentifier: {
        present: self.flagOf(draft, 'pki_ext_skid'), critical: false
      },
      authorityKeyIdentifier: {
        present: self.flagOf(draft, 'pki_ext_akid'), critical: false,
        includeIssuerAndSerial: self.flagOf(draft, 'pki_akid_issuer_serial')
      },
      subjectAltName: {
        present: self.flagOf(draft, 'pki_ext_san'),
        names: self.parseAltNames(self.linesOf(draft, 'pki_san')),
        critical: self.flagOf(draft, 'pki_san_critical')
      },
      issuerAltName: {
        present: self.flagOf(draft, 'pki_ext_ian'),
        names: self.parseAltNames(self.linesOf(draft, 'pki_ian')),
        critical: self.flagOf(draft, 'pki_ian_critical')
      },
      cRLDistributionPoints: {
        present: self.flagOf(draft, 'pki_ext_cdp'),
        urls: self.linesOf(draft, 'pki_cdp'),
        critical: self.flagOf(draft, 'pki_cdp_critical')
      },
      freshestCRL: {
        present: self.flagOf(draft, 'pki_ext_freshest'),
        urls: self.linesOf(draft, 'pki_freshest'),
        critical: false
      },
      authorityInfoAccess: {
        present: self.flagOf(draft, 'pki_ext_aia'),
        entries: self.parseAccessDescriptions(self.linesOf(draft, 'pki_aia')),
        critical: false
      },
      subjectInfoAccess: {
        present: self.flagOf(draft, 'pki_ext_sia'),
        entries: self.parseAccessDescriptions(self.linesOf(draft, 'pki_sia')),
        critical: false
      },
      certificatePolicies: {
        present: self.flagOf(draft, 'pki_ext_policies'),
        policies: self.parsePolicies(self.linesOf(draft, 'pki_policies')),
        critical: self.flagOf(draft, 'pki_policies_critical')
      },
      policyMappings: {
        present: self.flagOf(draft, 'pki_ext_policy_mappings'),
        mappings: self.parsePolicyMappings(
          self.linesOf(draft, 'pki_policy_mappings')),
        // RFC 5280 section 4.2.1.5 says this SHOULD be critical, and the parent
        // page hard-codes it for that reason rather than offering a box that
        // makes a certificate nothing profiles.
        critical: true
      },
      policyConstraints: {
        present: self.flagOf(draft, 'pki_ext_policy_constraints'),
        requireExplicitPolicy:
          self.textOf(draft, 'pki_require_explicit_policy'),
        inhibitPolicyMapping: self.textOf(draft, 'pki_inhibit_policy_mapping'),
        // RFC 5280 section 4.2.1.11: MUST be critical.
        critical: true
      },
      nameConstraints: {
        present: self.flagOf(draft, 'pki_ext_name_constraints'),
        permitted: constraints.permitted,
        excluded: constraints.excluded,
        critical: self.flagOf(draft, 'pki_nc_critical')
      },
      inhibitAnyPolicy: {
        present: self.flagOf(draft, 'pki_ext_inhibit_any'),
        skipCerts: self.textOf(draft, 'pki_inhibit_any_skip'),
        // RFC 5280 section 4.2.1.14: MUST be critical.
        critical: true
      },
      privateKeyUsagePeriod: {
        present: self.flagOf(draft, 'pki_ext_pkup'),
        notBefore: self.textOf(draft, 'pki_pkup_not_before'),
        notAfter: self.textOf(draft, 'pki_pkup_not_after'),
        critical: false
      },
      tlsFeature: {
        present: self.flagOf(draft, 'pki_ext_tls_feature'),
        features: self.linesOf(draft, 'pki_tls_feature'),
        critical: false
      },
      ocspNoCheck: {
        present: self.flagOf(draft, 'pki_ext_ocsp_nocheck'), critical: false
      },
      netscapeCertType: {
        present: self.flagOf(draft, 'pki_ext_ns_cert_type'),
        types: ticked('pki_ns_', x509.NS_CERT_TYPE_BITS.map(function (bit) {
          return bit.name;
        })),
        critical: false
      },
      netscapeComment: {
        present: self.flagOf(draft, 'pki_ext_ns_comment'),
        text: self.textOf(draft, 'pki_ns_comment'), critical: false
      },
      custom: self.parseCustomExtensions(
        self.linesOf(draft, 'pki_custom_extensions'))
    };
    log.debug('Leaving PkiAuthoring.extensionsFrom().');
    return ext;
  }

  // ---------------------------------------------------------------------------
  // THE PROFILES, AND WHAT PICKING ONE DOES.
  // ---------------------------------------------------------------------------
  profiles() {
    const { log, x509 } = this.deps;
    log.debug("Entering PkiAuthoring.profiles().");
    log.debug("Leaving PkiAuthoring.profiles().");
    return x509.profileIds().map(function (id) {
      const p = x509.profile(id) || {};
      return { id: id, label: p.label || id, ca: !!p.ca,
               selfSigned: !!p.selfSigned, years: p.years || 1,
               keyUsage: (p.keyUsage || []).slice(),
               extKeyUsage: (p.extKeyUsage || []).slice(),
               pathLen: p.pathLen === undefined ? null : p.pathLen,
               note: p.note || '' };
    });
  }

  profileFor(profileId: unknown) {
    const { log, x509 } = this.deps;
    log.debug("Entering PkiAuthoring.profileFor().");
    log.debug("Leaving PkiAuthoring.profileFor().");
    return x509.profile(String(profileId || '')) || null;
  }

  defaultProfileId() {
    const { log, x509 } = this.deps;
    log.debug("Entering PkiAuthoring.defaultProfileId().");
    log.debug("Leaving PkiAuthoring.defaultProfileId().");
    return x509.profileIds()[0];
  }

  // **THE FORM IS THE EXTENSION SET**, so applying a profile REWRITES the boxes
  // rather than remembering an intention. A profile that changed what gets
  // issued and not what is shown would be a page that lies about what it is
  // about to do, which is the parent page's own sentence for this function.
  //
  // The three subject rules are that page's as well, and the third is the one
  // that matters: a CN somebody TYPED is never overwritten, because this runs
  // on every profile change and a name typed a minute ago would otherwise be
  // replaced by a page that had merely been redrawn.
  applyProfile(draft: Draft, profileId: unknown): Draft {
    const self = this;
    const { log, x509 } = this.deps;
    log.debug('Entering PkiAuthoring.applyProfile(). profile=' + profileId);
    const id = self.profileFor(profileId) ? String(profileId)
                                          : self.defaultProfileId();
    const out = Object.assign({}, draft, { pki_profile: id });
    const ext = x509.defaultExtensions(id);
    const p = x509.profile(id) || {};

    out.pki_ext_bc = !!ext.basicConstraints.present;
    out.pki_bc_ca = !!ext.basicConstraints.ca;
    out.pki_bc_critical = !!ext.basicConstraints.critical;
    out.pki_bc_pathlen = (ext.basicConstraints.pathLen === null ||
                          ext.basicConstraints.pathLen === undefined)
      ? '' : String(ext.basicConstraints.pathLen);

    out.pki_ext_ku = !!ext.keyUsage.present;
    out.pki_ku_critical = !!ext.keyUsage.critical;
    x509.KEY_USAGE_BITS.forEach(function (bit) {
      out['pki_ku_' + bit.name] = ext.keyUsage.usages.indexOf(bit.name) >= 0;
    });

    out.pki_ext_eku = !!ext.extKeyUsage.present;
    out.pki_eku_critical = !!ext.extKeyUsage.critical;
    Object.keys(x509.EKU_OIDS).forEach(function (name) {
      out['pki_eku_' + name] = ext.extKeyUsage.usages.indexOf(name) >= 0;
    });

    out.pki_ext_skid = !!ext.subjectKeyIdentifier.present;
    out.pki_ext_akid = !!ext.authorityKeyIdentifier.present;
    out.pki_ext_ocsp_nocheck = !!ext.ocspNoCheck.present;

    // The validity follows the profile unless somebody typed one: twenty years
    // for a root and one for a leaf are what the profile IS, and a form that
    // kept the last profile's number would issue a one-year Root CA.
    const years = self.textOf(draft, 'pki_validity_years');
    if (!years || Number(years) === self.lastProfileYears(draft)) {
      out.pki_validity_years = String(p.years || 1);
    }

    // The CN: empty, or still ANY profile's default, is replaced. Picking
    // Intermediate CA after Root CA otherwise issues an intermediate called
    // "RootCA", which chains correctly and reads as a bug for as long as it
    // takes somebody to notice.
    const cn = self.textOf(draft, 'pki_dn_cn');
    if (!cn || x509.isDefaultSubjectCN(cn)) {
      out.pki_dn_cn = x509.defaultSubjectCN(id);
    }

    // The rest of the DN is filled ONCE into whatever is empty: it does not
    // follow the profile, and a field somebody deliberately emptied coming back
    // is the same trade the parent page makes.
    [['O', 'pki_dn_o'], ['OU', 'pki_dn_ou'], ['L', 'pki_dn_l'],
     ['ST', 'pki_dn_st'], ['C', 'pki_dn_c']].forEach(function (pair) {
      if (!self.textOf(out, pair[1])) {
        out[pair[1]] = x509.DEFAULT_DN[pair[0]] || '';
      }
    });

    // The subjectAltName, which only the serverAuth profiles have, follows the
    // CN rather than the profile's own default — for a TLS server that is the
    // difference between a certificate a client accepts and one it does not,
    // because every current browser ignores the Common Name. It is rewritten
    // only where it is still ours: any profile's default, or exactly what the
    // CN says.
    const san = self.textOf(draft, 'pki_san');
    const ours = !san || x509.isDefaultSubjectAltName(san) ||
                 (!!out.pki_dn_cn && san === 'dns:' + out.pki_dn_cn);
    if (ours) {
      let wanted = x509.defaultSubjectAltName(id);
      if (wanted && out.pki_dn_cn) {
        wanted = 'dns:' + out.pki_dn_cn;
      }
      out.pki_san = wanted || '';
      out.pki_ext_san = !!wanted;
    }

    log.debug('Leaving PkiAuthoring.applyProfile().');
    return out;
  }

  // What the PREVIOUS profile's default validity was, so that a number this
  // page put there can be told from one somebody typed. It is read off the
  // draft's own profile field rather than remembered, because there is nowhere
  // to remember it — the form is the state.
  private lastProfileYears(draft: Draft): number {
    const self = this;
    const { log } = this.deps;
    log.debug("Entering PkiAuthoring.lastProfileYears().");
    const p = self.profileFor(self.textOf(draft, 'pki_profile'));
    log.debug("Leaving PkiAuthoring.lastProfileYears().");
    return p ? (p.years || 1) : -1;
  }

  // ---------------------------------------------------------------------------
  // WHICH ALGORITHMS AN APPROACH ALLOWS.
  // ---------------------------------------------------------------------------
  // ---------------------------------------------------------------------------
  // THE PANE'S CLOSED FIELDS, REFUSED OUTSIDE THEIR SETS (#86).
  //
  // Five of the pane's fields take one of a fixed list, and two of them
  // quietly became something else when they held another value: an unknown
  // `pki_profile` was applied as the DEFAULT profile, and an unknown
  // `pki_pq_mode` narrowed the menus as `any`. The other three were refused,
  // but only by the step that happened to read them. The form's POST names no
  // `action` of its own (the pressed button does), so the console gate's
  // closed-set register has nothing to hold it to — this is the check, for
  // the console and `/admin-api` alike, and it runs before any pane action.
  // Empty is the field's default, as it always was.
  // ---------------------------------------------------------------------------
  closedFieldProblem(draft: Draft): Outcome | null {
    const self = this;
    const { log, x509, keyMaterial, errorCodes } = this.deps;
    log.debug("Entering PkiAuthoring.closedFieldProblem().");
    const sets: Array<[string, string[]]> = [
      ['pki_profile', x509.profileIds()],
      ['pki_pq_mode', PQ_MODE_IDS.slice()],
      ['pki_key_alg', keyMaterial.keyAlgIds()],
      ['pki_alt_key_alg', keyMaterial.keyAlgIds()],
      ['pki_ks_format', keyMaterial.keystoreFormats()]
    ];
    for (let i = 0; i < sets.length; i++) {
      const name = sets[i][0];
      const values = sets[i][1];
      const value = self.textOf(draft, name);
      if (value !== '' && values.indexOf(value) < 0) {
        log.debug("Leaving PkiAuthoring.closedFieldProblem(). " + name + ".");
        return errorCodes.mark({ ok: false, draft: draft,
                 errors: ['"' + name + '" is "' + value + '", which is not ' +
                          'one of the ' + values.length + ' values it ' +
                          'accepts: ' + values.map(function (v) {
                            return '"' + v + '"';
                          }).join(', ') + '.'] }, 'STS-PKI-0200');
      }
    }
    log.debug("Leaving PkiAuthoring.closedFieldProblem(). None.");
    return null;
  }

  pqModes() {
    const { log } = this.deps;
    log.debug("Entering PkiAuthoring.pqModes().");
    log.debug("Leaving PkiAuthoring.pqModes().");
    return PQ_MODES.map(function (one) {
      return Object.assign({}, one);
    });
  }

  pqModeFor(id: unknown) {
    const { log } = this.deps;
    log.debug("Entering PkiAuthoring.pqModeFor().");
    log.debug("Leaving PkiAuthoring.pqModeFor().");
    return PQ_MODES.filter(function (one) {
      return one.id === String(id || '');
    })[0] || PQ_MODES[0];
  }

  // The key algorithms this approach allows, in the registry's order, each with
  // the family it is grouped under. Forty-one flat options is a scroll bar with
  // no landmarks in it, and the families are the only grouping the standards
  // themselves have.
  keyAlgorithms(pqModeId: unknown) {
    const self = this;
    const { log, keyMaterial } = this.deps;
    log.debug('Entering PkiAuthoring.keyAlgorithms(). mode=' + pqModeId);
    const mode = self.pqModeFor(pqModeId);
    const out = keyMaterial.keyAlgIds().filter(function (id) {
      const desc = keyMaterial.KEY_ALGS[id];
      if (desc.kind !== 'pqc') {
        return mode.classical;
      }
      return mode.families.indexOf(desc.family) >= 0;
    }).map(function (id) {
      const desc = keyMaterial.KEY_ALGS[id];
      return { id: id, label: desc.label,
               family: desc.kind === 'pqc' ? desc.family : 'Classical',
               kind: desc.kind,
               // ML-KEM is a legitimate SUBJECT key and can never be an ISSUER
               // key: it establishes keys and signs nothing. The page says so
               // rather than offering a signature menu that cannot work.
               signs: desc.kind !== 'pqc' || desc.use !== 'kem',
               slow: desc.kind === 'pqc' &&
                     SLOW_FAMILIES.indexOf(desc.family) >= 0 };
    });
    log.debug('Leaving PkiAuthoring.keyAlgorithms(). ' +
              out.length + ' of them.');
    return out;
  }

  // The alternative key's menu: the post-quantum SIGNATURE algorithms, because
  // a hybrid certificate whose second key is also RSA is a certificate signed
  // twice by the same century.
  alternativeKeyAlgorithms() {
    const self = this;
    const { log } = this.deps;
    log.debug("Entering PkiAuthoring.alternativeKeyAlgorithms().");
    log.debug("Leaving PkiAuthoring.alternativeKeyAlgorithms().");
    return self.keyAlgorithms('pure').filter(function (one) {
      return one.signs;
    });
  }

  // The descriptor of whatever will actually SIGN: the issuer's key for an
  // issued certificate, the subject's own for a self-signed one. Getting this
  // the wrong way round produces a certificate whose declared algorithm and
  // actual signature disagree, which `openssl verify` reports as a bad
  // signature naming neither.
  signerDescriptorFor(realmId: string, draft: Draft) {
    const self = this;
    const { log, pki, keyMaterial } = this.deps;
    log.debug('Entering PkiAuthoring.signerDescriptorFor().');
    const p = self.profileFor(self.textOf(draft, 'pki_profile'));
    if (p && p.selfSigned) {
      log.debug('Leaving PkiAuthoring.signerDescriptorFor(). ' +
                'Self-signed: the subject key.');
      return keyMaterial.keyAlg(self.textOf(draft, 'pki_key_alg')) || null;
    }
    const issuer = pki.issuerFor(realmId, self.textOf(draft, 'pki_issuer'));
    if (issuer) {
      log.debug('Leaving PkiAuthoring.signerDescriptorFor(). The ' +
                'issuer\'s key.');
      return keyMaterial.keyAlg(issuer.keyAlg) || null;
    }
    log.debug('Leaving PkiAuthoring.signerDescriptorFor(). ' +
              'No issuer chosen yet.');
    return keyMaterial.keyAlg(self.textOf(draft, 'pki_key_alg')) || null;
  }

  // The signature algorithms that signing key can produce. An RSA key cannot
  // make an ECDSA signature, and offering it produces a Web Crypto error that
  // names neither.
  signatureAlgorithms(signerDesc: any) {
    const { log, x509 } = this.deps;
    log.debug('Entering PkiAuthoring.signatureAlgorithms().');
    const out = x509.signatureAlgorithmsFor(signerDesc || {})
      .map(function (id) {
        const spec = x509.SIG_ALGS[id] || {};
        return { id: id, label: spec.label || id, weak: !!spec.weak,
                 kind: spec.kind };
      });
    log.debug('Leaving PkiAuthoring.signatureAlgorithms(). ' +
              out.length + ' of them.');
    return out;
  }

  // ---------------------------------------------------------------------------
  // GENERATING A KEY PAIR INTO THE FORM. The button that does this WITHOUT
  // issuing exists because the pane's own reuse checkbox needs something to
  // reuse, and because generating an SLH-DSA pair takes seconds — doing it once
  // and then issuing four certificates from it is the difference between a page
  // somebody can use and one they cannot.
  // ---------------------------------------------------------------------------
  async generateKeys(draft: Draft, which?: string): Promise<Outcome> {
    const self = this;
    const { log, config, pki, errorCodes, keyMaterial } = this.deps;
    log.debug('Entering PkiAuthoring.generateKeys(). which=' + which);
    const alternative = which === 'alt';
    const algField = alternative ? 'pki_alt_key_alg' : 'pki_key_alg';
    const algId = self.textOf(draft, algField) ||
                  (alternative ? (self.alternativeKeyAlgorithms()[0] || {}).id
                               : config.value('pki.keyAlgorithm'));
    const desc = keyMaterial.keyAlg(algId);
    if (!desc) {
      log.debug('Leaving PkiAuthoring.generateKeys(). Unknown algorithm.');
      return errorCodes.mark({ ok: false,
               errors: ['"' + algId + '" is not a key algorithm this service ' +
                        'can generate.'] }, 'STS-PKI-0002');
    }
    let pair;
    try {
      pair = await keyMaterial.generateKeyPair(algId);
    } catch (e) {
      log.error(errorCodes.tag('STS-PKI-0075') + 'pki_authoring: a ' + algId +
                ' ' +
                'key pair could not be generated: ' + e.message);
      log.debug('Leaving PkiAuthoring.generateKeys(). The generator refused.');
      return errorCodes.mark({ ok: false,
               errors: ['A ' + desc.label + ' key pair could not be ' +
                        'generated: ' + e.message] }, 'STS-PKI-0075');
    }
    const out = Object.assign({}, draft);
    out[algField] = algId;
    const shown = await self.asShown(draft, pair, desc);
    out[alternative ? 'pki_alt_private_key' :
        'pki_private_key'] = shown.privateText;
    out[alternative ? 'pki_alt_public_key' :
        'pki_public_key'] = shown.publicText;
    log.debug('Leaving PkiAuthoring.generateKeys(). ' + desc.label + '.');
    return { ok: true, draft: out, algorithm: desc.label,
             why: 'A ' + desc.label + ' key pair was generated. It is in the ' +
                  'two boxes below and nothing has been issued for it yet — ' +
                  'tick "reuse the key pair below" and issue, or issue ' +
                  'without it and a fresh pair is made.' };
  }

  // PEM unless the JWK box is ticked. The conversion is key material only — the
  // same key either way — and it goes through the vendored module so that the
  // two pages produce the same JWK for the same key.
  //
  // **A POST-QUANTUM PAIR IS SHOWN AS PEM WHATEVER THE BOX SAYS.** The AKP JWK
  // (RFC 9964) exists, but the pane's two boxes are also the INPUT for a reuse,
  // and a round trip through a representation this encoder cannot read back
  // would lose the key. Saying so beats silently ignoring the box.
  private async asShown(draft: Draft,
                        pair: { privatePem: string; publicPem: string },
                        desc: any):
      Promise<{ privateText: string; publicText: string }> {
    const self = this;
    const { log, errorCodes, keyMaterial } = this.deps;
    log.debug('Entering PkiAuthoring.asShown().');
    if (!self.flagOf(draft, 'pki_key_jwk') || desc.kind === 'pqc') {
      log.debug('Leaving PkiAuthoring.asShown(). PEM.');
      return { privateText: pair.privatePem, publicText: pair.publicPem };
    }
    try {
      const jwks = await keyMaterial.keysToJwk(pair.privatePem, pair.publicPem,
                                               desc);
      log.debug('Leaving PkiAuthoring.asShown(). JWK.');
      return { privateText: JSON.stringify(jwks.privateKey, null, 2),
               publicText: JSON.stringify(jwks.publicKey, null, 2) };
    } catch (e) {
      // Not fatal: the key exists and PEM is what this page's other half reads.
      // A pair that could not be shown as JWK is still a pair.
      log.warn(errorCodes.tag('STS-PKI-0076') + 'pki_authoring: the key ' +
               'pair could not be rendered as JWK (' +
               e.message + '), so it is shown as PEM.');
      log.debug('Leaving PkiAuthoring.asShown(). ' +
                'PEM after a failed conversion.');
      return { privateText: pair.privatePem, publicText: pair.publicPem };
    }
  }

  // ---------------------------------------------------------------------------
  // ISSUING.
  //
  // Everything the pane can say ends up here: the key pair (generated or
  // reused), the issuer, the serial, the validity, the subject, the twenty-two
  // extensions, the hybrid half, and the certification request.
  // ---------------------------------------------------------------------------
  async issue(realmId: string, draft: Draft): Promise<Outcome> {
    const self = this;
    const { log, config, pki, errorCodes, x509, keyMaterial } = this.deps;
    log.debug('Entering PkiAuthoring.issue().');
    const profileId = self.textOf(draft, 'pki_profile') ||
                      self.defaultProfileId();
    const p = self.profileFor(profileId);
    if (!p) {
      log.debug('Leaving PkiAuthoring.issue(). Unknown profile.');
      return errorCodes.mark({ ok: false,
               errors: ['"' + profileId + '" is not a certificate profile ' +
                        'this service knows. They are ' +
                        x509.profileIds().join(', ') + '.'] }, 'STS-PKI-0077');
    }

    let subject;
    let extensions;
    try {
      subject = self.subjectFrom(draft);
      extensions = self.extensionsFrom(draft);
    } catch (e) {
      // A GRAMMAR error, and it names the line it could not read. Refused here
      // rather than passed on: a certificate quietly missing a name somebody
      // typed is the worst outcome available on this page, because it verifies.
      log.debug('Leaving PkiAuthoring.issue(). A field would not parse.');
      return errorCodes.mark({ ok: false, errors: [e.message] },
                             errorCodes.codeOf(e) || 'STS-PKI-0084');
    }
    if (!subject.length) {
      log.debug('Leaving PkiAuthoring.issue(). No subject.');
      return errorCodes.mark({ ok: false,
               errors: ['A certificate needs a subject — at least a Common ' +
                        'Name.'] }, 'STS-PKI-0085');
    }

    // THE STORE IS ASKED FIRST (2026-09-12). `pki.putObject()` REFUSES a new
    // object once `pki.maxStoredObjects` is reached rather than evicting the
    // oldest — which may carry a private key somebody chose to keep — and this
    // function did not read that answer, so issuing into a full store reported
    // "Issued" and stored nothing. Asked here, before the key generation,
    // because a post-quantum pair can take seconds and a refusal after them is
    // seconds spent on an object nobody may keep; the answer from `putObject()`
    // below is still checked, for the case where the store filled in between.
    if (!pki.roomForObject(realmId)) {
      log.debug('Leaving PkiAuthoring.issue(). The object store is full.');
      return errorCodes.mark({ ok: false,
               errors: ['This realm\'s certificate store is full (' +
                        'pki.maxStoredObjects is ' +
                        config.value('pki.maxStoredObjects') + '). ' +
                        'Nothing was generated and nothing already stored ' +
                        'was discarded. ' +
                        'Delete objects that are no longer wanted, or raise ' +
                        'pki.maxStoredObjects.'] }, 'STS-PKI-0027');
    }

    // --- the key pair ------------------------------------------------------
    const keyAlgId = self.textOf(draft, 'pki_key_alg') ||
                     config.value('pki.keyAlgorithm');
    const keyDesc = keyMaterial.keyAlg(keyAlgId);
    if (!keyDesc) {
      log.debug('Leaving PkiAuthoring.issue(). Unknown key algorithm.');
      return errorCodes.mark({ ok: false,
               errors: ['"' + keyAlgId + '" is not a key algorithm this ' +
                        'service can generate.'] }, 'STS-PKI-0002');
    }
    let privatePem = '';
    let publicPem = '';
    if (self.flagOf(draft, 'pki_reuse_key')) {
      const priv = String(draft.pki_private_key || '').trim();
      const pub = String(draft.pki_public_key || '').trim();
      if (!priv || !pub) {
        log.debug('Leaving PkiAuthoring.issue(). Nothing to reuse.');
        return errorCodes.mark({ ok: false,
                 errors: ['"reuse the key pair below" is ticked and the two ' +
                          'key boxes are not both filled in. Clear the box ' +
                          'and the button generates a pair: the certificate ' +
                          'certifies the public key, and a CA needs the ' +
                          'private half to go on signing with ' +
                          'afterwards.'] }, 'STS-PKI-0086');
      }
      try {
        // The boxes may hold JWK — the format toggle — and everything below is
        // PEM. One conversion, here, rather than at three call sites.
        privatePem = await keyMaterial.asPrivatePem(priv, keyDesc);
        publicPem = await keyMaterial.asPublicPem(pub, keyDesc);
      } catch (e) {
        log.debug('Leaving PkiAuthoring.issue(). ' +
                  'The pasted key would not read.');
        return errorCodes.mark({ ok: false,
                 errors: ['The key pair in the boxes could not be read as ' +
                          keyDesc.label + ': ' + e.message + ' Check that ' +
                          'the Key Algorithm above matches what is actually ' +
                          'in them.'] }, 'STS-PKI-0087');
      }
    } else {
      try {
        const pair = await keyMaterial.generateKeyPair(keyAlgId);
        privatePem = pair.privatePem;
        publicPem = pair.publicPem;
      } catch (e) {
        log.error(errorCodes.tag('STS-PKI-0075') + 'pki_authoring: a ' +
                  keyAlgId + ' ' +
                  'key pair could not be generated: ' + e.message);
        log.debug('Leaving PkiAuthoring.issue(). The generator refused.');
        return errorCodes.mark({ ok: false,
                 errors: ['A ' + keyDesc.label + ' key pair could not be ' +
                          'generated: ' + e.message] }, 'STS-PKI-0075');
      }
    }

    // --- the issuer --------------------------------------------------------
    let issuer = null;
    if (!p.selfSigned) {
      issuer = pki.issuerFor(realmId, self.textOf(draft, 'pki_issuer'));
      if (!issuer) {
        log.debug('Leaving PkiAuthoring.issue(). No issuer.');
        return errorCodes.mark({ ok: false,
                 errors: ['Choose the certificate authority that signs this ' +
                          'certificate. Build this realm\'s hierarchy above, ' +
                          'or issue a self-signed Root CA from this pane ' +
                          'first — a certificate signed by nothing is not ' +
                          'something this page can make except under a ' +
                          'self-signed ' +
                          'profile.'] }, 'STS-PKI-0088');
      }
      if (!issuer.privateKeyPem) {
        log.debug('Leaving PkiAuthoring.issue(). The issuer cannot sign.');
        return errorCodes.mark({ ok: false,
                 errors: ['"' + issuer.subject + '" has no private key in ' +
                          'this service, so it cannot sign.'] },
                               'STS-PKI-0089');
      }
    }

    // --- the signature algorithm -------------------------------------------
    const signerDesc = issuer ? keyMaterial.keyAlg(issuer.keyAlg) : keyDesc;
    const sigAlgId = self.textOf(draft, 'pki_sig_alg') ||
                     x509.defaultSignatureAlgorithm(signerDesc || {});
    const sig = x509.SIG_ALGS[sigAlgId];
    if (!sig) {
      log.debug('Leaving PkiAuthoring.issue(). Unknown signature algorithm.');
      return errorCodes.mark({ ok: false,
               errors: ['"' + sigAlgId + '" is not a signature algorithm ' +
                        'this service can produce.'] }, 'STS-PKI-0003');
    }
    const allowed = x509.signatureAlgorithmsFor(signerDesc || {});
    if (allowed.indexOf(sigAlgId) < 0) {
      // Refused here rather than left to the primitive, which reports it as a
      // key-usage error naming neither the key nor the algorithm. The list is
      // in the sentence because the page cannot narrow the menu without a
      // script.
      log.debug('Leaving PkiAuthoring.issue(). The algorithms do not match.');
      return errorCodes.mark({ ok: false,
               errors: ['The signing key is ' +
                        ((signerDesc || {}).label || 'of another kind') +
                        ', which cannot produce a ' + (sig.label || sigAlgId) +
                        ' signature. It can produce: ' + allowed.join(', ') +
                        '.'] }, 'STS-PKI-0004');
    }

    // --- validity ----------------------------------------------------------
    const notBeforeText = self.textOf(draft, 'pki_not_before');
    const notBefore = notBeforeText ? new Date(notBeforeText) : new Date();
    if (isNaN(notBefore.getTime())) {
      log.debug("Leaving PkiAuthoring.issue().");
      return errorCodes.mark({ ok: false, errors: ['Not Before is not a date ' +
                                   'this service can read: ' +
                                   '"' + notBeforeText + '".'] },
                             'STS-PKI-0090');
    }
    const notAfterText = self.textOf(draft, 'pki_not_after');
    let notAfter;
    if (notAfterText) {
      notAfter = new Date(notAfterText);
      if (isNaN(notAfter.getTime())) {
        log.debug("Leaving PkiAuthoring.issue().");
        return errorCodes.mark({ ok: false,
                                 errors: ['Not After is not a date ' +
                                     'this service can read: ' +
                                     '"' + notAfterText + '".'] },
                               'STS-PKI-0090');
      }
    } else {
      let years = parseInt(self.textOf(draft, 'pki_validity_years'), 10);
      if (!(years > 0)) {
        years = p.years || 1;
      }
      notAfter = new Date(notBefore.getTime());
      notAfter.setUTCFullYear(notAfter.getUTCFullYear() + years);
    }
    if (notAfter.getTime() <= notBefore.getTime()) {
      log.debug("Leaving PkiAuthoring.issue().");
      return errorCodes.mark({ ok: false,
               errors: ['Not After is not later than Not Before, so this ' +
                        'certificate would be expired the moment it was ' +
                        'signed.'] }, 'STS-PKI-0091');
    }

    const keepPrivate = self.flagOf(draft, 'pki_save_keys');
    const serial = self.textOf(draft, 'pki_serial') || x509.randomSerialHex(16);
    const spec: Record<string, any> = {
      profile: profileId,
      subject: subject,
      subjectPublicKey: publicPem,
      issuer: issuer
        ? { certificatePem: issuer.certificatePem,
            privateKeyPem: issuer.privateKeyPem, keyAlg: issuer.keyAlg }
        : null,
      issuerPrivateKey: issuer ? null : privatePem,
      signatureAlg: sigAlgId,
      serial: serial,
      notBefore: notBefore,
      notAfter: notAfter,
      extensions: extensions
    };

    // --- the hybrid half ---------------------------------------------------
    //
    // The subject's alternative PUBLIC key always goes in when this approach is
    // chosen; the alternative SIGNATURE only when there is an alternative
    // private key to make it with — the issuer's for an issued certificate,
    // this pair's own for a self-signed one. A certificate with the key and no
    // signature is a legitimate intermediate state (clause 9.8 says so
    // explicitly) rather than a failure, and the reply says which one was made.
    let alt = null;
    let altNote = '';
    if (self.textOf(draft, 'pki_pq_mode') === 'hybrid') {
      const made = await self.alternativePairFor(draft);
      if (!made.ok) {
        log.debug('Leaving PkiAuthoring.issue(). The alternative pair failed.');
        return made;
      }
      alt = made.pair;
      spec.subjectAltPublicKey = alt.publicPem;
      const altSignerPem = issuer ? issuer.altPrivateKeyPem : alt.privatePem;
      const altSignerAlg = issuer ? issuer.altKeyAlg : alt.algId;
      if (altSignerPem && altSignerAlg) {
        spec.altSignature = { signatureAlg: altSignerAlg,
                              privateKeyPem: altSignerPem,
                              keyAlg: altSignerAlg };
        altNote = ' It also carries an alternative ' +
                  (keyMaterial.KEY_ALGS[alt.algId] || {}).label +
                  ' key and a SECOND signature by ' +
                  (keyMaterial.KEY_ALGS[altSignerAlg] || {}).label + '.';
      } else {
        altNote = ' It carries an alternative ' +
                  (keyMaterial.KEY_ALGS[alt.algId] || {}).label +
                  ' key and NO alternative signature, because the issuer has ' +
                  'no alternative key of its own.';
      }
    }

    let result;
    try {
      result = await x509.issueCertificate(spec);
    } catch (e) {
      log.error(errorCodes.tag('STS-PKI-0092') + 'pki_authoring: a ' +
                'certificate for "' +
                self.textOf(draft, 'pki_dn_cn') + '" could not be issued: ' +
                e.message);
      log.debug('Leaving PkiAuthoring.issue(). The encoder refused.');
      return errorCodes.mark({ ok: false,
               errors: ['The certificate could not be issued: ' + e.message] },
                             'STS-PKI-0092');
    }

    // --- the certification request, which this page does not consume -------
    //
    // A CSR is what you send to an authority that will NOT take a certificate
    // you made yourself, and this page IS the authority. So it is built for
    // reference, from the SAME subject, key pair and extensions the certificate
    // was — a request assembled from a second reading of the form would differ
    // in ways nobody could see, and the one question a reader brings to it
    // ("is this the request for that certificate?") would have no answer.
    //
    // A failure here never fails the issue: the certificate is the product and
    // the request is a note beside it.
    let csrPem = '';
    let csrNote = '';
    if (self.flagOf(draft, 'pki_gen_csr')) {
      try {
        const request = await x509.certificationRequest({
          subject: subject,
          publicKeyPem: publicPem,
          privateKeyPem: privatePem,
          signatureAlg: sigAlgId,
          keyUsage: extensions.keyUsage.present
            ? extensions.keyUsage.usages : [],
          extKeyUsage: extensions.extKeyUsage.present
            ? extensions.extKeyUsage.usages : [],
          basicConstraints: extensions.basicConstraints.present
            ? extensions.basicConstraints : null,
          subjectAltName: extensions.subjectAltName.present
            ? extensions.subjectAltName.names : []
        });
        csrPem = request.pem;
      } catch (e) {
        log.warn(errorCodes.tag('STS-PKI-0093') + 'pki_authoring: the ' +
                 'certificate was issued and the CSR could not be ' +
                 'built: ' + e.message);
        csrNote = ' The certification request could NOT be built (' +
                  e.message + '), which has no effect on the certificate.';
      }
    }

    // --- into the store ----------------------------------------------------
    const object = {
      id: self.newObjectId(p.ca ? 'ca' : 'leaf'),
      ca: !!p.ca,
      profile: profileId,
      profileLabel: p.label || profileId,
      subject: result.subject,
      issuerId: issuer ? issuer.id : null,
      issuerSubject: result.issuer,
      selfSigned: !issuer,
      serialHex: result.serialHex,
      keyAlg: keyDesc.id,
      keyAlgLabel: keyDesc.label,
      signatureAlg: result.signatureAlg,
      signatureAlgLabel: sig.label || result.signatureAlg,
      pqMode: self.textOf(draft, 'pki_pq_mode') || 'any',
      certificatePem: result.pem,
      // Dropped HERE rather than at a caller, so that a private key this pane
      // was told not to keep cannot reach the store by a route somebody forgot
      // about. The form still holds the pair it just certified — discarding it
      // from the SCREEN as well would be a page that generated a key, used it,
      // and refused to show it to the person who asked for it.
      privateKeyPem: keepPrivate ? privatePem : '',
      publicKeyPem: publicPem,
      csrPem: csrPem,
      altKeyAlg: alt ? alt.algId : null,
      altPrivateKeyPem: alt ? alt.privatePem : null,
      altPublicKeyPem: alt ? alt.publicPem : null,
      altSigned: !!spec.altSignature,
      notBefore: result.notBefore,
      notAfter: result.notAfter,
      thumbprint: pki.thumbprintOf(result.pem),
      createdAt: Date.now()
    };
    const stored = pki.putObject(realmId, object);
    if (!stored || stored.ok === false) {
      log.debug('Leaving PkiAuthoring.issue(). The store refused the object.');
      return errorCodes.mark({ ok: false, draft: draft,
               errors: (stored && stored.errors) ||
                       ['The certificate was built and could not be stored.'] },
               errorCodes.codeOf(stored) || 'STS-PKI-0094');
    }

    // The form comes back with a FRESH SERIAL and the key pair that was just
    // certified. A serial that stayed put would be re-used by the next
    // certificate the same authority signs, and two certificates from one
    // issuer sharing a serial is exactly what a serial exists to prevent: they
    // are indistinguishable to anything that revokes, caches or pins by
    // (issuer, serial).
    const next = Object.assign({}, draft, {
      pki_serial: x509.randomSerialHex(16),
      pki_csr: csrPem,
      pki_selected: object.id
    });
    const shownPair = await self.asShown(draft, { privatePem: privatePem,
                                             publicPem: publicPem }, keyDesc);
    next.pki_private_key = shownPair.privateText;
    next.pki_public_key = shownPair.publicText;
    if (alt) {
      next.pki_alt_private_key = alt.privatePem;
      next.pki_alt_public_key = alt.publicPem;
    }

    log.info('pki_authoring: a ' + (p.label || profileId) + ' certificate ' +
             'was issued in the "' + (realmId || 'default') + '" realm for ' +
             result.subject + ', serial ' + result.serialHex + ', signed ' +
             (sig.label || sigAlgId) + ' by ' +
             (issuer ? issuer.subject : 'itself') + '.');
    log.debug('Leaving PkiAuthoring.issue(). ' + object.id);
    return { ok: true, object: object, draft: next,
             dropped: stored.dropped,
             why: 'Issued "' + result.subject + '", serial ' +
                  result.serialHex.slice(0, 16) + '…, signed with ' +
                  (sig.label || sigAlgId) + ' by ' +
                  (issuer ? '"' + issuer.subject + '"' : 'itself') + '.' +
                  altNote + csrNote +
                  (keepPrivate ? ''
                    : ' ITS PRIVATE KEY WAS NOT KEPT — "keep the private key ' +
                      'in this service" is cleared — so the stored object ' +
                      'cannot sign, cannot be exported and cannot be used as ' +
                      'an issuer. It is still in the key boxes on the form, ' +
                      'which is the only copy there is.') +
                  (stored.dropped
                    ? ' The store was full, so ' + stored.dropped + ' of the ' +
                      'oldest object(s) went to make room.'
                    : '') };
  }

  // The alternative key pair for a hybrid certificate: reused from the boxes
  // when the box says so, generated otherwise.
  private async alternativePairFor(draft: Draft): Promise<Outcome> {
    const self = this;
    const { log, errorCodes, keyMaterial } = this.deps;
    log.debug('Entering PkiAuthoring.alternativePairFor().');
    const algId = self.textOf(draft, 'pki_alt_key_alg') ||
                  (self.alternativeKeyAlgorithms()[0] || {}).id;
    const desc = keyMaterial.keyAlg(algId);
    if (!desc) {
      log.debug('Leaving PkiAuthoring.alternativePairFor(). ' +
                'Unknown algorithm.');
      return errorCodes.mark({ ok: false,
               errors: ['"' + algId + '" is not an algorithm this service ' +
                        'can use for the alternative key.'] },
                             'STS-PKI-0002');
    }
    const priv = String(draft.pki_alt_private_key || '').trim();
    const pub = String(draft.pki_alt_public_key || '').trim();
    if (self.flagOf(draft, 'pki_alt_reuse_key') || (priv && pub)) {
      if (!priv || !pub) {
        log.debug('Leaving PkiAuthoring.alternativePairFor(). Half a pair.');
        return errorCodes.mark({ ok: false,
                 errors: ['The alternative key pair is half filled in. Both ' +
                          'boxes, or neither and one is generated.'] },
                               'STS-PKI-0095');
      }
      log.debug('Leaving PkiAuthoring.alternativePairFor(). Reused.');
      return { ok: true, pair: { algId: algId, privatePem: priv,
                                 publicPem: pub } };
    }
    try {
      const pair = await keyMaterial.generateKeyPair(algId);
      log.debug('Leaving PkiAuthoring.alternativePairFor(). Generated.');
      return { ok: true, pair: { algId: algId, privatePem: pair.privatePem,
                                 publicPem: pair.publicPem } };
    } catch (e) {
      log.debug('Leaving PkiAuthoring.alternativePairFor(). ' +
                'The generator refused.');
      return errorCodes.mark({ ok: false,
               errors: ['The alternative ' + desc.label + ' key pair could ' +
                        'not be generated: ' + e.message] }, 'STS-PKI-0075');
    }
  }

  // An id for a stored object. Random rather than sequential: these are written
  // into form values and into `/admin-api` replies, and a counter would make
  // one realm's third object and another's the same string.
  private newObjectId(prefix: string): string {
    const { log, nodeCrypto } = this.deps;
    log.debug("Entering PkiAuthoring.newObjectId().");
    log.debug("Leaving PkiAuthoring.newObjectId().");
    return prefix + '-' + nodeCrypto.randomBytes(8).toString('hex');
  }

  // ---------------------------------------------------------------------------
  // LOADING A STORED OBJECT'S KEY PAIR BACK INTO THE FORM — the pane's *Use
  // this key pair*, which is what re-issuing for an existing key (a CA renewing
  // its own certificate) is done with. It ticks the reuse box itself, because a
  // pair loaded into the boxes and then silently replaced by a fresh one at the
  // next issue is the single most confusing thing this pane could do.
  // ---------------------------------------------------------------------------
  async useStoredKey(realmId: string, draft: Draft,
                     objectId: string): Promise<Outcome> {
    const self = this;
    const { log, pki, errorCodes, keyMaterial } = this.deps;
    log.debug('Entering PkiAuthoring.useStoredKey(). id=' + objectId);
    const object = pki.objectFor(realmId, objectId);
    if (!object) {
      log.debug('Leaving PkiAuthoring.useStoredKey(). No such object.');
      return errorCodes.mark({ ok: false,
               errors: ['There is no object "' + objectId + '" in this ' +
                        'realm\'s store.'] }, 'STS-PKI-0029');
    }
    if (!object.privateKeyPem) {
      log.debug('Leaving PkiAuthoring.useStoredKey(). No private key.');
      return errorCodes.mark({ ok: false,
               errors: ['"' + object.subject + '" has no private key here, ' +
                        'so there is no pair to reuse.'] }, 'STS-PKI-0096');
    }
    const desc = keyMaterial.keyAlg(object.keyAlg) || {};
    const shown = await self.asShown(draft,
                                     { privatePem: object.privateKeyPem,
                                       publicPem: object.publicKeyPem },
                                     desc);
    const out = Object.assign({}, draft, {
      pki_key_alg: object.keyAlg,
      pki_reuse_key: true,
      pki_private_key: shown.privateText,
      pki_public_key: shown.publicText,
      pki_selected: object.id
    });
    if (object.altPrivateKeyPem) {
      out.pki_alt_key_alg = object.altKeyAlg || '';
      out.pki_alt_private_key = object.altPrivateKeyPem;
      out.pki_alt_public_key = object.altPublicKeyPem || '';
      out.pki_alt_reuse_key = true;
    }
    log.debug('Leaving PkiAuthoring.useStoredKey(). Loaded.');
    return { ok: true, draft: out,
             why: 'The ' + (desc.label || object.keyAlg) + ' key pair of "' +
                  object.subject + '" is in the key boxes and "reuse the key ' +
                  'pair below" is ticked, so the next issue CERTIFIES THIS ' +
                  'KEY rather than generating a new one.' };
  }

  // ---------------------------------------------------------------------------
  // THE CHAIN ABOVE AN OBJECT, leaf-FIRST, walked through the store and then
  // through the hierarchy's tiers.
  //
  // It is capped, and the cap is not paranoia: `issuerId` is a value in a store
  // an operator can edit through `/admin-api`, and an object naming itself — or
  // two naming each other — would otherwise walk for ever inside a request.
  // ---------------------------------------------------------------------------
  chainFor(realmId: string, object: any): string[] {
    const self = this;
    const { log, pki, errorCodes } = this.deps;
    log.debug('Entering PkiAuthoring.chainFor().');
    const out = [];
    const seen = {};
    let current = object;
    let hops = 0;
    while (current && hops < 16) {
      hops += 1;
      if (seen[current.id || current.tier]) {
        log.warn(errorCodes.tag('STS-PKI-0097') + 'pki_authoring: the chain ' +
                                                  'above ' +
                                                  '"' + object.subject + '" ' +
                 'loops back on itself at "' + current.subject + '", so the ' +
                 'walk stopped there. An issuer id was edited into a cycle.');
        break;
      }
      seen[current.id || current.tier] = true;
      if (current !== object) {
        out.push(current.certificatePem);
      }
      if (!current.issuerId) {
        break;
      }
      const next = pki.issuerFor(realmId, current.issuerId);
      if (!next) {
        log.debug('PkiAuthoring.chainFor(): the issuer of "' +
                  current.subject + '" is not in this realm any more, so ' +
                  'the chain stops there.');
        break;
      }
      // A tier knows its own parent implicitly; `issuers()` answers tiers with
      // no `issuerId`, so the walk continues through the hierarchy by ORDER.
      current = Object.assign({}, next,
                              { issuerId: self.parentTierOf(realmId, next) });
    }
    log.debug('Leaving PkiAuthoring.chainFor(). ' +
              out.length + ' certificate(s) above it.');
    return out;
  }

  // The id of the tier above this one, or null. The hierarchy is built root
  // first, so the parent of tier N is tier N-1 and the Root's parent is
  // nothing.
  private parentTierOf(realmId: string, issuer: any): string | null {
    const { log, pki } = this.deps;
    log.debug("Entering PkiAuthoring.parentTierOf().");
    if (!issuer || !issuer.tier) {
      log.debug("Leaving PkiAuthoring.parentTierOf().");
      return issuer ? issuer.issuerId || null : null;
    }
    const index = pki.TIER_IDS.indexOf(issuer.tier);
    if (index <= 0) {
      log.debug("Leaving PkiAuthoring.parentTierOf().");
      return null;
    }
    log.debug("Leaving PkiAuthoring.parentTierOf().");
    return 'tier:' + pki.TIER_IDS[index - 1];
  }

  // ---------------------------------------------------------------------------
  // EXPORT: PEM, DER, a JWK set or a password-protected PKCS#12.
  //
  // **THE EXPORT IS `common/vendored/key_material.js`'s, NOT A SECOND ONE** —
  // the same function `/admin/keys` uses, which is what makes a `.p12` from
  // this pane and one from that page import identically into keytool, OpenSSL,
  // Windows and macOS.
  //
  // `ONE FILE IS THE BODY; SEVERAL ARE A ZIP THIS SERVICE WILL NOT BUILD` is
  // `admin-ui/crypto_metadata.ts`'s rule and it holds here: the DER export is
  // two files and only the private one is sent, with the reply saying the
  // public half comes out of it with one openssl command.
  // ---------------------------------------------------------------------------
  async exportKeys(realmId: string, draft: Draft,
                   objectId?: string): Promise<Outcome> {
    const self = this;
    const { log, config, pki, errorCodes, keyMaterial } = this.deps;
    log.debug('Entering PkiAuthoring.exportKeys(). object=' + objectId);
    const format = self.textOf(draft, 'pki_ks_format') || 'pem';
    if (keyMaterial.keystoreFormats().indexOf(format) < 0) {
      log.debug('Leaving PkiAuthoring.exportKeys(). Unknown format.');
      return errorCodes.mark({ ok: false,
               errors: ['"' + format + '" is not a keystore format. They are ' +
                        keyMaterial.keystoreFormats().join(', ') + '.'] },
                             'STS-PKI-0098');
    }
    const password = String(draft.pki_ks_password || '');
    const object = objectId ? pki.objectFor(realmId, objectId) : null;
    if (objectId && !object) {
      log.debug('Leaving PkiAuthoring.exportKeys(). No such object.');
      return errorCodes.mark({ ok: false,
               errors: ['There is no object "' + objectId + '" in this ' +
                        'realm\'s store.'] }, 'STS-PKI-0029');
    }

    // The SELECTED object if one was named, otherwise whatever is in the two
    // key boxes — which is the parent page's rule and is what makes the Export
    // row useful before anything has been issued.
    const keyAlgId = object ? object.keyAlg
      : (self.textOf(draft, 'pki_key_alg') ||
         config.value('pki.keyAlgorithm'));
    const desc = keyMaterial.keyAlg(keyAlgId);
    if (!desc) {
      log.debug("Leaving PkiAuthoring.exportKeys().");
      return errorCodes.mark({ ok: false,
               errors: ['"' + keyAlgId + '" is not a key algorithm this ' +
                        'service knows, so its key pair cannot be written ' +
                        'out.'] }, 'STS-PKI-0002');
    }
    const privateText = object ? object.privateKeyPem
                               : String(draft.pki_private_key || '').trim();
    const publicText = object ? object.publicKeyPem
                              : String(draft.pki_public_key || '').trim();
    if (!privateText || !publicText) {
      log.debug('Leaving PkiAuthoring.exportKeys(). No key pair.');
      return errorCodes.mark({ ok: false,
               errors: ['There is no key pair to export. Generate one, or ' +
                        'select an object in the store below.'] },
                             'STS-PKI-0099');
    }

    const certs = [];
    if (object) {
      certs.push(object.certificatePem);
      if (self.flagOf(draft, 'pki_ks_include_chain')) {
        self.chainFor(realmId, object).forEach(function (pem) {
          certs.push(pem);
        });
      }
    }
    let written;
    try {
      written = await keyMaterial.exportKeyPair({
        format: format,
        password: password,
        privatePem: privateText,
        publicPem: publicText,
        desc: desc,
        certs: certs,
        baseName: self.fileBaseFor(object, desc),
        friendlyName: object ? object.subject : 'sts key pair'
      });
    } catch (e) {
      log.debug('Leaving PkiAuthoring.exportKeys(). The export refused.');
      return errorCodes.mark({ ok: false, errors: [e.message] },
                             'STS-PKI-0100');
    }
    log.debug('Leaving PkiAuthoring.exportKeys(). ' +
              written.files.length + ' file(s).');
    return { ok: true, files: written.files, status: written.status,
             // Said rather than silently dropped — see the rule above.
             truncated: written.files.length > 1 };
  }

  // A file name a person can find again: the subject's CN where there is one,
  // the algorithm where there is not, and nothing in it a file system will
  // argue with.
  private fileBaseFor(object: any, desc: any): string {
    const { log } = this.deps;
    log.debug("Entering PkiAuthoring.fileBaseFor().");
    const from = object ? object.subject : (desc.label || 'key-pair');
    const cn = /CN=([^,]+)/.exec(from);
    const stem = (cn ? cn[1] : from).trim() || 'key-pair';
    log.debug("Leaving PkiAuthoring.fileBaseFor().");
    return stem.replace(/[^A-Za-z0-9._-]+/g, '-').slice(0, 60);
  }

  // ---------------------------------------------------------------------------
  // THE VIEW: everything the page and `GET /admin-api/pki` need to DRAW the
  // pane, out of one function so the two cannot disagree about what it offers.
  //
  // **NO PRIVATE KEY IS IN IT.** A stored object is reported by what it IS; the
  // key material comes out only through the export, which is a POST behind
  // Admin Write for the reason `/admin/keys/export` is.
  // ---------------------------------------------------------------------------
  view(realmId: string, draft?: Draft | null) {
    const self = this;
    const { log, pki, x509, keyMaterial } = this.deps;
    log.debug('Entering PkiAuthoring.view().');
    const current = draft || self.defaultDraft(realmId);
    const signerDesc = self.signerDescriptorFor(realmId, current);
    const out = {
      fields: FIELD_NAMES.slice(),
      profiles: self.profiles(),
      pqModes: self.pqModes(),
      pqMode: self.textOf(current, 'pki_pq_mode') || 'any',
      keyAlgorithms: self.keyAlgorithms(
        self.textOf(current, 'pki_pq_mode') || 'any'),
      alternativeKeyAlgorithms: self.alternativeKeyAlgorithms(),
      signatureAlgorithms: self.signatureAlgorithms(signerDesc),
      signerLabel: signerDesc ? (signerDesc.label || signerDesc.kind) : '',
      keystoreFormats: keyMaterial.keystoreFormats(),
      keyUsageBits: x509.KEY_USAGE_BITS.map(function (bit) {
        return { name: bit.name, what: bit.what || '' };
      }),
      extendedKeyUsages: Object.keys(x509.EKU_OIDS).map(function (name) {
        return { name: name, oid: x509.EKU_OIDS[name] };
      }),
      netscapeTypes: x509.NS_CERT_TYPE_BITS.map(function (bit) {
        return { name: bit.name };
      }),
      accessMethods: Object.keys(x509.AIA_METHODS),
      dnFields: DN_FIELDS.slice(),
      issuers: pki.issuers(realmId).map(function (one) {
        return { id: one.id, label: one.label, subject: one.subject,
                 keyAlg: one.keyAlg, notAfter: one.notAfter,
                 hasAlternativeKey: !!one.altPrivateKeyPem };
      }),
      objects: pki.objects(realmId).map(function (one) {
        return self.describeObject(one);
      }),
      maxObjects: pki.MAX_OBJECTS,
      slowFamilies: SLOW_FAMILIES.slice(),
      draft: current
    };
    log.debug('Leaving PkiAuthoring.view(). ' +
              out.objects.length + ' object(s).');
    return out;
  }

  // One stored object as it is REPORTED — no private key, and the certificate
  // in full because a certificate is the half of a key pair meant to be handed
  // around.
  describeObject(one: any) {
    const { log } = this.deps;
    log.debug("Entering PkiAuthoring.describeObject().");
    log.debug("Leaving PkiAuthoring.describeObject().");
    return {
      id: one.id,
      ca: !!one.ca,
      profile: one.profile,
      profileLabel: one.profileLabel,
      subject: one.subject,
      issuerSubject: one.issuerSubject,
      issuerId: one.issuerId,
      selfSigned: !!one.selfSigned,
      serialHex: one.serialHex,
      keyAlg: one.keyAlg,
      keyAlgLabel: one.keyAlgLabel,
      signatureAlg: one.signatureAlg,
      signatureAlgLabel: one.signatureAlgLabel,
      pqMode: one.pqMode,
      altKeyAlg: one.altKeyAlg || null,
      altSigned: !!one.altSigned,
      notBefore: one.notBefore,
      notAfter: one.notAfter,
      expired: new Date(one.notAfter).getTime() < Date.now(),
      thumbprint: one.thumbprint,
      createdAt: one.createdAt,
      hasPrivateKey: !!one.privateKeyPem,
      hasCsr: !!one.csrPem,
      certificatePem: one.certificatePem,
      csrPem: one.csrPem || ''
    };
  }

  // The form as it is first drawn: every field at its default, the configured
  // key algorithm, this realm's own organisation, the first profile applied,
  // and a serial ready to be signed.
  //
  // **THE SERIAL IS FILLED RATHER THAN LEFT EMPTY** so that the value about to
  // be signed is visible — and editable — before the certificate exists,
  // instead of appearing for the first time in the store's Serial column.
  defaultDraft(realmId: string): Draft {
    const self = this;
    const { log, config, pki, x509 } = this.deps;
    log.debug('Entering PkiAuthoring.defaultDraft().');
    const draft = self.draftFrom({});
    draft.pki_key_alg = config.value('pki.keyAlgorithm');
    draft.pki_alt_key_alg = (self.alternativeKeyAlgorithms()[0] || {}).id || '';
    draft.pki_serial = x509.randomSerialHex(16);
    draft.pki_ks_include_chain = true;
    draft.pki_save_keys = true;
    draft.pki_dn_o = config.value('pki.organisation');
    const applied = self.applyProfile(draft, self.defaultProfileId());
    // The organisation is this service's setting rather than the encoder's
    // example, because a hierarchy built on the page above carries it and two
    // certificates from one realm reading `O=Example` and `O=sts` are two
    // organisations as far as a path validator is concerned.
    applied.pki_dn_o = config.value('pki.organisation');
    // An issuer is preselected where there is exactly one obvious answer — this
    // realm's Issuing CA, which is the tier that signs everything this service
    // hands out.
    const issuers = pki.issuers(realmId);
    const issuing = issuers.filter(function (one) {
      return one.tier === 'issuing';
    })[0];
    applied.pki_issuer =
      (issuing || issuers[issuers.length - 1] || {}).id || '';
    log.debug('Leaving PkiAuthoring.defaultDraft().');
    return applied;
  }
}

// ---------------------------------------------------------------------------
// THE INSTANCE, BUILT BY THE COMPOSITION ROOT (#50, R2). This module builds no
// instance of its own: `common/protocol_stack.ts` builds one and calls
// `installInstance()`. The exports below are FACADES that forward to that
// instance, for the JavaScript that still calls this module through
// `require()`; a process that never runs the root gets a default instance,
// built from `defaultDeps()` when this module finishes loading (see
// `common/instance_slot.ts`).
// ---------------------------------------------------------------------------
const slot = new InstanceSlot<PkiAuthoring>(
  'common/pki_authoring',
  () => new PkiAuthoring(PkiAuthoring.defaultDeps()),
  null,
  log);

// Standalone, build the default now, as loading this module always did.
slot.buildNowUnlessDeferred();

export = {
  PkiAuthoring: PkiAuthoring,
  installInstance: (instance: PkiAuthoring): void => slot.install(instance),
  instanceOrigin: (): string => slot.origin(),
  FIELDS: PkiAuthoring.FIELDS,
  FIELD_NAMES: PkiAuthoring.FIELD_NAMES,
  DN_FIELDS: PkiAuthoring.DN_FIELDS,
  PQ_MODES: PkiAuthoring.PQ_MODES,
  PQ_MODE_IDS: PkiAuthoring.PQ_MODE_IDS,
  SLOW_FAMILIES: PkiAuthoring.SLOW_FAMILIES,
  draftFrom: slot.forward('draftFrom'),
  defaultDraft: slot.forward('defaultDraft'),
  applyProfile: slot.forward('applyProfile'),
  closedFieldProblem: slot.forward('closedFieldProblem'),
  profiles: slot.forward('profiles'),
  profileFor: slot.forward('profileFor'),
  defaultProfileId: slot.forward('defaultProfileId'),
  pqModes: slot.forward('pqModes'),
  pqModeFor: slot.forward('pqModeFor'),
  keyAlgorithms: slot.forward('keyAlgorithms'),
  alternativeKeyAlgorithms: slot.forward('alternativeKeyAlgorithms'),
  signerDescriptorFor: slot.forward('signerDescriptorFor'),
  signatureAlgorithms: slot.forward('signatureAlgorithms'),
  subjectFrom: slot.forward('subjectFrom'),
  extensionsFrom: slot.forward('extensionsFrom'),
  parseAltNames: slot.forward('parseAltNames'),
  parseAccessDescriptions: slot.forward('parseAccessDescriptions'),
  parsePolicies: slot.forward('parsePolicies'),
  parsePolicyMappings: slot.forward('parsePolicyMappings'),
  parseNameConstraints: slot.forward('parseNameConstraints'),
  parseCustomExtensions: slot.forward('parseCustomExtensions'),
  linesOf: slot.forward('linesOf'),
  generateKeys: slot.forward('generateKeys'),
  issue: slot.forward('issue'),
  useStoredKey: slot.forward('useStoredKey'),
  chainFor: slot.forward('chainFor'),
  exportKeys: slot.forward('exportKeys'),
  describeObject: slot.forward('describeObject'),
  view: slot.forward('view')
};
