'use strict';
//
// File: secrets.js
//
// ---------------------------------------------------------------------------
// WHERE THE KEY-ENCRYPTION KEY COMES FROM (2026-09-06).
//
// Product mode writes this service's signing keys to the persistence store,
// encrypted with AES-256-GCM (see `crypto.js`'s `encryptWithKek()`). That moves
// the problem rather than solving it — the ciphertext is only as safe as the key
// that opens it — so the KEK itself is never stored by this service, never
// generated by it, and never written to its configuration. It is READ, at
// startup, from somewhere outside.
//
// **FIVE PLACES, ONE INTERFACE.** A provider is an object with `read()`, which
// answers the secret (bytes or text — `crypto.kekBytes()` decides the shape) or
// throws with a sentence saying what to fix.
//
//   file    a path mounted into the container. THE DEFAULT, because it needs
//           nothing: Kubernetes mounts a Secret as a file, Docker mounts a
//           secret as a file, and a developer can `openssl rand -base64 32 >`
//           one. Every other provider here is that same idea with somebody
//           else's access control in front of it.
//   aws     AWS Secrets Manager
//   gcp     Google Cloud Secret Manager
//   azure   Azure Key Vault
//   vault   HashiCorp Vault
//
// ---------------------------------------------------------------------------
// THE FOUR CLOUD ADAPTERS LAZILY REQUIRE THEIR OFFICIAL SDK, AND THAT IS A
// DEPENDENCY DECISION RATHER THAN A STYLE ONE.
//
// Each SDK is large — the AWS one alone dwarfs everything else in this
// package's tree — and **this service is a mock first**: the debugger suite
// installs it, CI installs it, and every one of those installs would carry four
// cloud SDKs to use none of them. Each adapter `require()`s its package INSIDE
// `read()`, and a missing package is reported as the one sentence that fixes it
// — the name to install — rather than as `Cannot find module`, which names a
// file nobody chose.
//
// **THEY ARE OPTIONAL *PEER* DEPENDENCIES AND NOT `optionalDependencies`, AND
// THE DIFFERENCE IS THE WHOLE POINT.** `optionalDependencies` means "install
// it, but do not fail the install if you cannot" — npm installs them by
// default, and `.npmrc`'s `omit=dev` does not touch them — so declaring them
// there would have carried all five into every checkout while the comment above
// claimed otherwise. A peer dependency marked `optional: true` in
// `peerDependenciesMeta` is NOT installed automatically: a deployment that
// wants one runs `npm install @aws-sdk/client-secrets-manager` and gets a
// version check against the range this package declares. That is the standard
// idiom for a pluggable adapter and it is the one that matches what is written
// here.
//
// **THEY ARE NOT HAND-ROLLED OVER REST**, which was the first instinct and the
// wrong one. Signing an AWS request is SigV4, and the failure mode of getting
// it subtly wrong is a service that cannot read its own signing key on a
// Tuesday. The SDKs also carry the credential chains — instance roles, workload
// identity, managed identity — which is most of what makes a secret manager
// usable at all, and none of which is a thing to reimplement.
//
// **NO SECRET IS EVER LOGGED, AND NO SECRET IS EVER CACHED ON DISK.** `read()`
// is called at startup and the value is held in memory by `keystore.js` for as
// long as the process runs. `describe()` says WHERE a provider reads from and
// never what it read.
//
// A LIBRARY (rule 3): it registers no route. It requires only `config` and
// `helpers` for the log.
// ---------------------------------------------------------------------------

const fs = require('fs');
// A LOGGER OF ITS OWN RATHER THAN helpers.js's, AND IT HAS TO BE.
// `helpers.js` requires this module — it is where the signing keys are built —
// so requiring it back would close a cycle, and a cycle in node does not fail
// loudly: it hands back a half-initialised module whose exports are
// `undefined`, and the symptom arrives later as something that is not a
// function (rule 2). `crypto.js` and `config.js` make their own for the same
// reason.
const bunyan = require('bunyan');
const config = require('./config');

const log = bunyan.createLogger({
  name: 'secrets',
  level: config.value('global.logLevel')
});

// One sentence for a missing SDK, so all four say the same thing the same way.
function missingModule(pkg, provider, err) {
  return new Error(
    'the "' + provider + '" key-encryption-key provider needs the ' + pkg +
    ' package and it is not installed. It is deliberately NOT a dependency of ' +
    'this service — it is a mock first, and four cloud SDKs nobody uses would ' +
    'be carried by every install. Run `npm install ' + pkg + '` in this ' +
    'deployment, or use keys.kekProvider=file, which needs nothing. The ' +
    'underlying error was: ' + err.message);
}

// ---------------------------------------------------------------------------
// file — THE DEFAULT.
//
// A path, read as bytes. It is the default because it is what every container
// platform already does: a Kubernetes Secret, a Docker secret and a mounted
// volume all arrive as a file, so the platform's own access control is the
// access control and this service adds none of its own.
//
// **THE FILE'S PERMISSIONS ARE CHECKED AND REPORTED RATHER THAN ENFORCED.** A
// world-readable key file is a real problem and refusing to start over it would
// be worse: the fix may be impossible inside a container whose mount the
// operator does not control, and a service that will not start is a service
// somebody works around by putting the key in an environment variable.
// ---------------------------------------------------------------------------
const fileProvider = {
  id: 'file',
  label: 'A file mounted into the container',
  describe: function () {
    return { from: config.value('keys.kekFile') || '(no path configured)' };
  },
  read: function () {
    log.debug('Entering fileProvider.read().');
    const path = String(config.value('keys.kekFile') || '').trim();
    if (!path) {
      throw new Error('keys.kekProvider is "file" and keys.kekFile names no ' +
                      'path. Set it (STS_KEYS_KEK_FILE) to a file holding at ' +
                      'least 32 bytes — `openssl rand -base64 32 > /run/secrets/sts-kek`.');
    }
    let stat = null;
    try {
      stat = fs.statSync(path);
    } catch (e) {
      throw new Error('the key-encryption key file "' + path + '" could not ' +
                      'be read: ' + e.message + '. In product mode this ' +
                      'service will not start without it, because the ' +
                      'alternative is generating a new signing key and ' +
                      'silently invalidating every token it ever issued.');
    }
    // Reported, not refused — see the header.
    if ((stat.mode & 0o077) !== 0) {
      log.warn('secrets: the key-encryption key file "' + path + '" is ' +
               'readable by group or other (mode ' +
               (stat.mode & 0o777).toString(8) + '). Every signing key this ' +
               'service holds is protected by it. `chmod 600` it.');
    }
    const body = fs.readFileSync(path);
    log.info('secrets: the key-encryption key was read from ' + path + '.');
    log.debug('Leaving fileProvider.read().');
    return body.toString('utf8').trim() || body;
  }
};

// ---------------------------------------------------------------------------
// aws — AWS Secrets Manager, through @aws-sdk/client-secrets-manager.
//
// The secret is named by `keys.kekRef`, which takes either a name or a full
// ARN; the SDK accepts both as `SecretId`. Region and credentials come from the
// SDK's own chain (environment, shared config, instance role, IRSA), which is
// the whole reason to use it rather than sign requests here.
// ---------------------------------------------------------------------------
const awsProvider = {
  id: 'aws',
  label: 'AWS Secrets Manager',
  describe: function () {
    return { from: config.value('keys.kekRef') || '(no secret id configured)',
             region: config.value('keys.kekRegion') || '(the SDK default)' };
  },
  read: async function () {
    log.debug('Entering awsProvider.read().');
    let sdk;
    try {
      sdk = require('@aws-sdk/client-secrets-manager');
    } catch (e) {
      throw missingModule('@aws-sdk/client-secrets-manager', 'aws', e);
    }
    const secretId = String(config.value('keys.kekRef') || '').trim();
    if (!secretId) {
      throw new Error('keys.kekProvider is "aws" and keys.kekRef names no ' +
                      'secret. Set it to the secret\'s name or ARN.');
    }
    const region = String(config.value('keys.kekRegion') || '').trim();
    const client = new sdk.SecretsManagerClient(region ? { region: region } : {});
    const answer = await client.send(
      new sdk.GetSecretValueCommand({ SecretId: secretId }));
    // A secret may be a string or binary, and both are legitimate here: a
    // pasted base64 key is a string, `aws secretsmanager put-secret-value
    // --secret-binary` is not.
    const value = answer.SecretString !== undefined && answer.SecretString !== null
      ? answer.SecretString
      : Buffer.from(answer.SecretBinary || [], 'base64');
    log.info('secrets: the key-encryption key was read from AWS Secrets ' +
             'Manager (' + secretId + ').');
    log.debug('Leaving awsProvider.read().');
    return value;
  }
};

// ---------------------------------------------------------------------------
// gcp — Google Cloud Secret Manager, through @google-cloud/secret-manager.
//
// `keys.kekRef` is the RESOURCE NAME and takes a version: a bare
// `projects/p/secrets/s` is completed with `/versions/latest`, because a
// deployment that pinned a version meant to and one that did not wants the
// current one.
// ---------------------------------------------------------------------------
const gcpProvider = {
  id: 'gcp',
  label: 'Google Cloud Secret Manager',
  describe: function () {
    return { from: config.value('keys.kekRef') || '(no resource name configured)' };
  },
  read: async function () {
    log.debug('Entering gcpProvider.read().');
    let sdk;
    try {
      sdk = require('@google-cloud/secret-manager');
    } catch (e) {
      throw missingModule('@google-cloud/secret-manager', 'gcp', e);
    }
    let name = String(config.value('keys.kekRef') || '').trim();
    if (!name) {
      throw new Error('keys.kekProvider is "gcp" and keys.kekRef names no ' +
                      'secret. Set it to projects/<project>/secrets/<name> ' +
                      '(a /versions/<n> suffix is optional).');
    }
    if (name.indexOf('/versions/') < 0) {
      name = name.replace(/\/+$/, '') + '/versions/latest';
    }
    const client = new sdk.SecretManagerServiceClient();
    const [answer] = await client.accessSecretVersion({ name: name });
    const payload = answer && answer.payload && answer.payload.data;
    if (!payload) {
      throw new Error('the secret version "' + name + '" carries no payload');
    }
    log.info('secrets: the key-encryption key was read from Google Cloud ' +
             'Secret Manager (' + name + ').');
    log.debug('Leaving gcpProvider.read().');
    return Buffer.from(payload).toString('utf8').trim();
  }
};

// ---------------------------------------------------------------------------
// azure — Azure Key Vault, through @azure/keyvault-secrets and @azure/identity.
//
// TWO packages rather than one, and both are needed: the client speaks to the
// vault and `DefaultAzureCredential` is what obtains the token — managed
// identity in Azure, environment variables or the developer's az login
// elsewhere. `keys.kekVault` is the vault URL and `keys.kekRef` the secret name.
// ---------------------------------------------------------------------------
const azureProvider = {
  id: 'azure',
  label: 'Azure Key Vault',
  describe: function () {
    return { from: config.value('keys.kekRef') || '(no secret name configured)',
             vault: config.value('keys.kekVault') || '(no vault url configured)' };
  },
  read: async function () {
    log.debug('Entering azureProvider.read().');
    let secretsSdk;
    let identitySdk;
    try {
      secretsSdk = require('@azure/keyvault-secrets');
    } catch (e) {
      throw missingModule('@azure/keyvault-secrets', 'azure', e);
    }
    try {
      identitySdk = require('@azure/identity');
    } catch (e) {
      throw missingModule('@azure/identity', 'azure', e);
    }
    const vault = String(config.value('keys.kekVault') || '').trim();
    const name = String(config.value('keys.kekRef') || '').trim();
    if (!vault || !name) {
      throw new Error('keys.kekProvider is "azure" and it needs both ' +
                      'keys.kekVault (https://<name>.vault.azure.net) and ' +
                      'keys.kekRef (the secret name).');
    }
    const client = new secretsSdk.SecretClient(
      vault, new identitySdk.DefaultAzureCredential());
    const answer = await client.getSecret(name);
    if (!answer || !answer.value) {
      throw new Error('the secret "' + name + '" in ' + vault + ' has no value');
    }
    log.info('secrets: the key-encryption key was read from Azure Key Vault (' +
             vault + ', ' + name + ').');
    log.debug('Leaving azureProvider.read().');
    return String(answer.value).trim();
  }
};

// ---------------------------------------------------------------------------
// vault — HashiCorp Vault, through node-vault.
//
// `keys.kekRef` is the read path and `keys.kekField` the field within the
// secret, defaulting to `value`. **BOTH KV ENGINE VERSIONS ARE HANDLED**: v2
// nests the data one level deeper (`data.data`) than v1 (`data`), the path
// differs too, and a deployment usually does not know which it is on — so the
// answer is unwrapped by shape rather than by a setting nobody can fill in
// correctly.
// ---------------------------------------------------------------------------
const vaultProvider = {
  id: 'vault',
  label: 'HashiCorp Vault',
  describe: function () {
    return { from: config.value('keys.kekRef') || '(no path configured)',
             endpoint: config.value('keys.kekVault') || '(VAULT_ADDR)',
             field: config.value('keys.kekField') || 'value' };
  },
  read: async function () {
    log.debug('Entering vaultProvider.read().');
    let sdk;
    try {
      sdk = require('node-vault');
    } catch (e) {
      throw missingModule('node-vault', 'vault', e);
    }
    const path = String(config.value('keys.kekRef') || '').trim();
    if (!path) {
      throw new Error('keys.kekProvider is "vault" and keys.kekRef names no ' +
                      'path. Set it to the read path, e.g. secret/data/sts-kek.');
    }
    const endpoint = String(config.value('keys.kekVault') || '').trim();
    const token = String(config.value('keys.kekToken') || '').trim();
    const client = sdk(Object.assign(
      { apiVersion: 'v1' },
      endpoint ? { endpoint: endpoint } : {},
      // The token falls back to the SDK's own VAULT_TOKEN handling, which is
      // what a deployment using an agent sidecar or an auth method relies on.
      token ? { token: token } : {}));
    const answer = await client.read(path);
    const field = String(config.value('keys.kekField') || 'value');
    const data = answer && answer.data;
    if (!data) {
      throw new Error('the Vault path "' + path + '" returned no data');
    }
    // KV v2 nests: { data: { data: { value: ... } } }. KV v1 does not.
    const holder = (data.data && typeof data.data === 'object') ? data.data : data;
    const value = holder[field];
    if (value === undefined || value === null || value === '') {
      throw new Error('the Vault path "' + path + '" has no "' + field + '" ' +
                      'field. It holds: ' + Object.keys(holder).join(', ') +
                      '. Set keys.kekField to one of those.');
    }
    log.info('secrets: the key-encryption key was read from HashiCorp Vault (' +
             path + ').');
    log.debug('Leaving vaultProvider.read().');
    return String(value).trim();
  }
};

const PROVIDERS = [fileProvider, awsProvider, gcpProvider, azureProvider,
                   vaultProvider];
const PROVIDER_IDS = PROVIDERS.map(function (one) { return one.id; });

function providerFor(id) {
  const wanted = String(id || 'file');
  return PROVIDERS.filter(function (one) { return one.id === wanted; })[0] || null;
}

// The configured one, read fresh each time because `keys.kekProvider` is a
// setting and a cached provider would be the one this process started with.
function current() {
  return providerFor(config.value('keys.kekProvider'));
}

// THE KEK. Asynchronous because four of the five providers are — a network
// call to somebody else's secret store — and the file one is made to look the
// same so that no caller has to know which is configured.
async function readKek() {
  log.debug('Entering readKek().');
  const provider = current();
  if (!provider) {
    throw new Error('keys.kekProvider is "' + config.value('keys.kekProvider') +
                    '", which is not one of: ' + PROVIDER_IDS.join(', ') + '.');
  }
  const value = await provider.read();
  log.debug('Leaving readKek(). Provider: ' + provider.id + '.');
  return value;
}

// WHERE THE KEY COMES FROM, for the console and the metadata report. It says
// WHERE and never WHAT: a page that printed the key-encryption key would be the
// single worst thing this service could draw.
function describe() {
  const provider = current();
  return {
    provider: provider ? provider.id : String(config.value('keys.kekProvider')),
    label: provider ? provider.label : 'unknown',
    known: !!provider,
    where: provider ? provider.describe() : {},
    providers: PROVIDERS.map(function (one) {
      return { id: one.id, label: one.label };
    })
  };
}

module.exports = {
  PROVIDER_IDS: PROVIDER_IDS,
  providerFor: providerFor,
  current: current,
  readKek: readKek,
  describe: describe
};
